### ISSUE TITLE
migration from marthoc not recognizing ConBee II 

### ISSUE THREAD

**Issue by cleggton** [deconz-community/deconz-docker#108]
I have migrated using the steps described from a functioning container using the Marthoc image. 

The container is running on a raspberry pi 4 (using Portainer for management)

I have followed the configuration steps, the web front end all comes up fine, but it doesn't seem to recognize the Conbee II stick, i.e. no firmware version provided.

![image](https://user-images.githubusercontent.com/25527565/166645632-7251ce73-7a50-41d4-a7e2-9054a155eb58.png)

The docker logs don't give me many clues:

`
[deconzcommunity/deconz] Starting deCONZ...
[deconzcommunity/deconz] Current deCONZ version: 2.13.01
[deconzcommunity/deconz] Web UI port: 80
[deconzcommunity/deconz] Websockets port: 443
[deconzcommunity/deconz] Using options --auto-connect=1         --appdata=/opt/deCONZ         --dbg-info=1         --dbg-aps=0         --dbg-zcl=0         --dbg-ddf=0         --dbg-dev=0         --dbg-zdp=0         --dbg-ota=0 	--dbg-error=0         --http-port=80         --ws-port=443
[deconzcommunity/deconz] Modifying user and group ID
[deconzcommunity/deconz] Checking device group ID
[deconzcommunity/deconz] VNC Disabled
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-deconz'
libpng warning: iCCP: known incorrect sRGB profile
This plugin does not support propagateSizeHints()
This plugin does not support propagateSizeHints()
This plugin does not support propagateSizeHints()
This plugin does not support propagateSizeHints()
`

**Comment by phdelodder** [comment]
Please check the device is passthrough?

**Comment by cleggton** [comment]
I have the device set here 

![image](https://user-images.githubusercontent.com/25527565/166679871-b8742755-7f81-4b3a-9b24-a08d84e42a4e.png)

and in the environment variables

![image](https://user-images.githubusercontent.com/25527565/166680111-d0a02347-b4d5-44c7-a40c-91d30be1cd80.png)

**Comment by phdelodder** [comment]
Can you add DECONZ_START_VERBOSE and set it to 1, hopefully there be some more info to work with

**Comment by cleggton** [comment]
Here is the log

`[deconzcommunity/deconz] Starting deCONZ...
[deconzcommunity/deconz] Current deCONZ version: 2.13.01
[deconzcommunity/deconz] Web UI port: 80
[deconzcommunity/deconz] Websockets port: 443
[deconzcommunity/deconz] Using options --auto-connect=1         --appdata=/opt/deCONZ         --dbg-info=1         --dbg-aps=0         --dbg-zcl=0         --dbg-ddf=0         --dbg-dev=0         --dbg-zdp=0         --dbg-ota=0 	--dbg-error=0         --http-port=80         --ws-port=443
[deconzcommunity/deconz] Modifying user and group ID
[deconzcommunity/deconz] Checking device group ID
+ echo [deconzcommunity/deconz] Starting deCONZ...
+ echo [deconzcommunity/deconz] Current deCONZ version: 2.13.01
+ echo [deconzcommunity/deconz] Web UI port: 80
+ echo [deconzcommunity/deconz] Websockets port: 443
+ DECONZ_OPTS=--auto-connect=1         --appdata=/opt/deCONZ         --dbg-info=1         --dbg-aps=0         --dbg-zcl=0         --dbg-ddf=0         --dbg-dev=0         --dbg-zdp=0         --dbg-ota=0 	--dbg-error=0         --http-port=80         --ws-port=443
+ echo [deconzcommunity/deconz] Using options --auto-connect=1         --appdata=/opt/deCONZ         --dbg-info=1         --dbg-aps=0         --dbg-zcl=0         --dbg-ddf=0         --dbg-dev=0         --dbg-zdp=0         --dbg-ota=0 	--dbg-error=0         --http-port=80         --ws-port=443
+ echo [deconzcommunity/deconz] Modifying user and group ID
+ [ 1000 != 1000 ]
+ [ 1000 != 1000 ]
+ echo [deconzcommunity/deconz] Checking device group ID
+ [ /dev/ttyACM1 != 0 ]
+ DEVICE=/dev/ttyACM1
+ stat --printf=%g /dev/ttyACM1
+ DIALOUTGROUPID=20
+ DIALOUTGROUPID=20
+ [ 20 != 20 ]
+ stat -c %A /dev/ttyACM1
      
+ cut -c 5-7
+ GROUPPERMISSIONS=rw-
+ [ rw- = --- ]
      
+ [ 0 != 0 ]
+ echo [deconzcommunity/deconz] VNC Disabled
+ DECONZ_OPTS=--auto-connect=1         --appdata=/opt/deCONZ         --dbg-info=1         --dbg-aps=0         --dbg-zcl=0         --dbg-ddf=0         --dbg-dev=0         --dbg-zdp=0         --dbg-ota=0 	--dbg-error=0         --http-port=80         --ws-port=443 -platform minimal
+ [ /dev/ttyACM1 != 0 ]
+ DECONZ_OPTS=--auto-connect=1         --appdata=/opt/deCONZ         --dbg-info=1         --dbg-aps=0         --dbg-zcl=0         --dbg-ddf=0         --dbg-dev=0         --dbg-zdp=0         --dbg-ota=0 	--dbg-error=0         --http-port=80         --ws-port=443 -platform minimal --dev=/dev/ttyACM1
      
+ [ 1 != 1 ]
+ mkdir -p /opt/deCONZ/otau
[deconzcommunity/deconz] VNC Disabled
+ ln -sfT /opt/deCONZ/otau /home/deconz/otau
+ chown deconz:deconz /home/deconz/otau
+ chown deconz:deconz /opt/deCONZ -R
+ exec gosu deconz /usr/bin/deCONZ --auto-connect=1 --appdata=/opt/deCONZ --dbg-info=1 --dbg-aps=0 --dbg-zcl=0 --dbg-ddf=0 --dbg-dev=0 --dbg-zdp=0 --dbg-ota=0 --dbg-error=0 --http-port=80 --ws-port=443 -platform minimal --dev=/dev/ttyACM1
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-deconz'
libpng warning: iCCP: known incorrect sRGB profile
This plugin does not support propagateSizeHints()
This plugin does not support propagateSizeHints()
This plugin does not support propagateSizeHints()
This plugin does not support propagateSizeHints()
QBasicTimer::start: Timers cannot have negative timeouts
`

**Comment by cleggton** [comment]
It is probably worth noting that I am using the stable tag for the container (i'm not sure that makes a difference)

**Comment by cleggton** [comment]
Interesting:  I just checked my running instance and downgraded to the same version deconzcommunity/deconz:2.13.02

This is working fine.  It doesn't suggest anything, could be a container build thing or a deconz thing - has anything changed significantly between the docker builds?

**Comment by cleggton** [comment]
There seem to be a similar issues, which point to power or an issue with bullseye - not sure how they apply here

https://forum.phoscon.de/t/conbee2-firmware-not-connected-v2-14-01-bullseye/1726/14
https://forum.phoscon.de/t/firmware-not-connected-again-and-again/1185/5
https://forum.phoscon.de/t/conbee2-firmware-not-connected-2-14-01-buster/1734/9

Power - can't see any evidence of the device unplugging in dmesg
OS - that's built into the container - a bunch of people seemed to have success rebuilding their pi installs (not docker)

I'm a bit lost here,

**Comment by Jo-Be-Co** [comment]
The differences could be seen here: [Diff to 2.13.04](https://github.com/deconz-community/deconz-docker/compare/2.13.04_stable...main#files_bucket).
I would say the github-workflows don't have any impact. So what remains:

- `debian:11.2-slim` instead of `debian:10.11-slim`
- `gosu` instead of `sudo`
- some `gosu/sudo` calls where replaced by direct calls
- VNC-stuff
- not to forget the new deCONZ-image itself

**Comment by Jo-Be-Co** [comment]
Maybe you could also check out `2.14.01_stable` so the delta would shrink (to one side or the other) ...

**Comment by cleggton** [comment]
2.14.01 seems fine

**Comment by Jo-Be-Co** [comment]
So the diff shrinks to [17 commits](https://github.com/deconz-community/deconz-docker/compare/2.14.01_stable...main#files_bucket).

The `sudo/gosu` part is already included in 2.14.01.

**Comment by cleggton** [comment]
the 2 that stand out are the change to the Deconz version and to the Debian base build, not sure I am in the position to debug or fix either of those even if i knew which was the problem

**Comment by phdelodder** [comment]
If you know the problem, I can try to find a solution. I can't reproduce so if you can find the exact root cause, that would be helpfull.

**Comment by cleggton** [comment]
Any clues where to look, the docker logs give very little. Any other logs to look at if I connect to the container?  Dmesg isn't available

**Comment by Jo-Be-Co** [comment]
You might also try `2.15.01_beta`. With this the [delta of 10 commits](https://github.com/deconz-community/deconz-docker/compare/2.15.01_beta...main) doesn't contain the debian update anymore ...

**Comment by cleggton** [comment]
what docker tag is that - i'm guessing 2.15.01??

![image](https://user-images.githubusercontent.com/25527565/167085186-ad388b28-35f7-4e24-862c-7dfa6149ba67.png)

**Comment by cleggton** [comment]
So 2.15.01 from the docker hub doesn't work

![image](https://user-images.githubusercontent.com/25527565/167086914-ea82810a-9ca9-4e8f-be7f-3caa2eadeb1b.png)

but it is giving me better logging for some reason.

[logs.txt](https://github.com/deconz-community/deconz-docker/files/8638366/logs.txt)

This line stands out

`06:49:56:373 gw run mode: docker
06:49:56:373 GW sd-card image version file does not exist: /opt/deCONZ/gw-version
06:49:56:373 sd-card cid: 035344534333324780ffffffff014600
`

**Comment by phdelodder** [comment]
In the log, there is `06:50:12:373 COM: /dev/ttyACM1 / serialno: , ConBee II` so it detects the device as a conbee II.

**Comment by cleggton** [comment]
exactly

**Comment by phdelodder** [comment]
So it's not docker issue, you should check why deconz doesn't read out the serial.

**Comment by cleggton** [comment]
would you recommend the deconz forum as a first port of call?

**Comment by phdelodder** [comment]
@Mimiix what would you propose?

**Comment by Mimiix** [comment]
I am not sure, we don't have any docker knowledge on the forums.  Stick not seen is not an issue which normally is in deconz itself, otherwise it could be a docker wide bug.

Can you provide some longer logs (when boot is complete and when trying to connect to network) with INFO / INFO_L2, ERROR, ERROR_L2 , APS, APS_L2 ?

**Comment by Mimiix** [comment]
You can add logging in the compose (check this repo's readme).

**Comment by cleggton** [comment]
so if i set

DEBUG_INFO=2
DEBUG_APS=2
DEBUG_ERROR=2

**Comment by Mimiix** [comment]
Yes, But you need to let it run longer. It's not even started at the moment you stop it already 😅

**Comment by phdelodder** [comment]
Can you try running it as root? by adding env vars: 
- `DECONZ_UID=0`
- `DECONZ_GID=0`

**Comment by Mimiix** [comment]
> That permission error also seems to happen in my functioning container, my device is ttyACM1

Wait, you have the old container still running?

**Comment by cleggton** [comment]
No, I stop it before starting the new one

**Comment by Mimiix** [comment]
Just a sidenote here (i'm checking the logs with Manup): I'm noticing that the timestamps are going all over the place.

**Comment by cleggton** [comment]
```
CONTAINER ID   IMAGE                                             COMMAND                  CREATED          STATUS                            PORTS                                                                                  NAMES
85e7ece0929c   deconzcommunity/deconz:latest                     "/start.sh"              24 minutes ago   Up About a minute (unhealthy)                                                                                            deconz_test
8ec38d2037f3   deconzcommunity/deconz:2.14.01                    "/start.sh"              17 hours ago     Exited (143) About a minute ago                                                                                          deconz
370cb2dd624c   homeassistant/raspberrypi4-homeassistant:stable   "/init"                  23 hours ago     Up 23 hours                                                                                                              home-assistant
fbd422b8051f   zwavejs/zwavejs2mqtt:latest                       "docker-entrypoint.s…"   3 days ago       Up 3 days                         0.0.0.0:3000->3000/tcp, :::3000->3000/tcp, 0.0.0.0:8091->8091/tcp, :::8091->8091/tcp   ZwaveJS
4c02a2aeb64d   portainer/agent                                   "./agent"                4 weeks ago      Up 4 weeks                        0.0.0.0:9001->9001/tcp, :::9001->9001/tcp                                              portainer_agent
ebf347a06ff3   nodered/node-red:latest                           "npm --no-update-not…"   2 months ago     Up 7 weeks (healthy)              0.0.0.0:1880->1880/tcp, :::1880->1880/tcp                                              nodered
d0aea54050de   containrrr/watchtower:latest                      "/watchtower --clean…"   3 months ago     Up 7 weeks                        8080/tcp                                                                               watchtower
4ac8a5164236   mikenye/virtualradarserver:latest                 "/init"                  14 months ago    Up 7 weeks                        0.0.0.0:8080->8080/tcp, :::8080->8080/tcp                                              virtual-radar
66a3fbc0110f   theappgineer/roon-extension-manager:latest        "docker-entrypoint.s…"   18 months ago    Up 5 hours                                                                                                               roon-extension-manager
```

**Comment by Mimiix** [comment]
The 2.14.0 was running when you made the log , correct?

**Comment by cleggton** [comment]
the latest log is 2.15:03 (latest tag), the previous log was 2.15:01.

2.14:01 is my container that is working and I haven't shared the logs from that

**Comment by senilio** [comment]
also share the output of `ls -l /dev/serial/by-id/`

**Comment by Mimiix** [comment]
That seems fine I suppose :)

Please provide the info i've requested 😅

**Comment by cleggton** [comment]
> 

Ok, so i think i have done all this but for the sake of removal of doubt and collecting everything into one place:

I absolutely am stopping one container before starting the other.

* stopped the 2.14.01 container and started the latest
* output of docker ps -a 

```
pi@node-2:~ $ docker ps -a
CONTAINER ID   IMAGE                                             COMMAND                  CREATED          STATUS                       PORTS                                                                                  NAMES
90c3a99eefb7   zwavejs/zwavejs2mqtt:latest                       "docker-entrypoint.s…"   36 minutes ago   Up 36 minutes                0.0.0.0:3000->3000/tcp, :::3000->3000/tcp, 0.0.0.0:8091->8091/tcp, :::8091->8091/tcp   ZwaveJS
e2df1ff99c68   homeassistant/raspberrypi4-homeassistant:stable   "/init"                  36 minutes ago   Up 36 minutes                                                                                                       home-assistant
85e7ece0929c   deconzcommunity/deconz:latest                     "/start.sh"              2 hours ago      Up 2 minutes (unhealthy)                                                                                            deconz_test
8ec38d2037f3   deconzcommunity/deconz:2.14.01                    "/start.sh"              19 hours ago     Exited (143) 3 minutes ago                                                                                          deconz
4c02a2aeb64d   portainer/agent                                   "./agent"                4 weeks ago      Up 4 weeks                   0.0.0.0:9001->9001/tcp, :::9001->9001/tcp                                              portainer_agent
ebf347a06ff3   nodered/node-red:latest                           "npm --no-update-not…"   2 months ago     Up 7 weeks (healthy)         0.0.0.0:1880->1880/tcp, :::1880->1880/tcp                                              nodered
d0aea54050de   containrrr/watchtower:latest                      "/watchtower --clean…"   3 months ago     Up 7 weeks                   8080/tcp                                                                               watchtower
4ac8a5164236   mikenye/virtualradarserver:latest                 "/init"                  14 months ago    Up 7 weeks                   0.0.0.0:8080->8080/tcp, :::8080->8080/tcp                                              virtual-radar
66a3fbc0110f   theappgineer/roon-extension-manager:latest        "docker-entrypoint.s…"   18 months ago    Up 7 hours                                                                                                          roon-extension-manager
```

logs from 2.15.03

[logs.txt](https://github.com/deconz-community/deconz-docker/files/8641322/logs.txt)

Checked behavior in phoscon

![image](https://user-images.githubusercontent.com/25527565/167151367-33d4f380-1db3-40c3-b6ef-044a786eab0e.png)

I don't use docker-compose as I use portainer for container management, so here is the output from the inspect 

[latest inspect.txt](https://github.com/deconz-community/deconz-docker/files/8641391/latest.inspect.txt)
[2.14.01 inspect.txt](https://github.com/deconz-community/deconz-docker/files/8641393/2.14.01.inspect.txt)


and finally the output from ls -l /dev/serial/by-id/

```
pi@node-2:~ $ ls -l /dev/serial/by-id/
total 0
lrwxrwxrwx 1 root root 13 Mar 12 13:19 usb-0658_0200-if00 -> ../../ttyACM0
lrwxrwxrwx 1 root root 13 Apr 25 20:35 usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2434325-if00 -> ../../ttyACM1

```

**Comment by Mimiix** [comment]
Your device in the latest inspect is not correcT:

2.14.01 inspect:
            "DECONZ_DEVICE=/dev/ttyACM1",

latest inspect:
            DECONZ_DEVICE=devttyACM1,

Same goes for path:
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",

latest:
            PATH=usrlocalsbinusrlocalbinusrsbinusrbinsbinbin,

Also some stuff missing on the health-check.


Image has also some differences. I looks like slashes are missing everywhere.

**Comment by cleggton** [comment]
The permisions we're 1000, before I changed them as per the above to potentially diagnose a permission issue.  I will revert, but am convinced it will make no difference.

I have changed the logging level on 2.14.01 to match the latest, so you can do an easy diff
[logs_2.14.02.txt](https://github.com/deconz-community/deconz-docker/files/8641597/logs_2.14.02.txt)

**Comment by cleggton** [comment]
ok, I have tried this a couple of times, but will have another go.

So i have literally duplicated the working container and changed the docker image to `latest`.  No joy

[logs_latest.txt](https://github.com/deconz-community/deconz-docker/files/8641710/logs_latest.txt)

I wonder if the timestamps points to something off in the "clock" in the OS, there was a base build update in the versions between 2.14 and latest

https://github.com/deconz-community/deconz-docker/compare/2.14.01_stable...main#files_bucket

@phdelodder is there anything potentially funky with the base image or config

**Comment by Mimiix** [comment]
The time is just odd, it really makes no sense that it jumps all over.  I have no clue why that happens.

**Comment by cleggton** [comment]
so had a look in the containers 

**2.14.01** 
![image](https://user-images.githubusercontent.com/25527565/167184086-c2605746-fd39-40ee-a9a2-5b09b84d056d.png)

**latest**
![image](https://user-images.githubusercontent.com/25527565/167184350-26e2de34-e860-434a-a4b7-be3daa142614.png)

This will be affecting the logging, if not everything else.

Not sure why the time isn't being set in the latest container

**Comment by cleggton** [comment]
Right I've found the problem.

I've done a whole host of digging, and the time issue in the container pointed me to the below.

It is the issue with libsecomp

https://docs.linuxserver.io/faq#libseccomp

Added the backports, updated and restarted the docker service, all good,.

**Comment by cleggton** [comment]
Right I've found the problem.

I've done a whole host of digging, and the time issue in the container pointed me to the below.

It is the issue with libsecomp

https://docs.linuxserver.io/faq#libseccomp

Added the backports, updated and restarted the docker service, all good,.

**Comment by Mimiix** [comment]
Happy it's solved and good to know that. Your welcome :)!

**Comment by cleggton** [comment]
Thanks for everyone's time and patience.

**Comment by Jo-Be-Co** [comment]
Wow - that was a stony road. Good to see you finally found the cause 👏 

Just for clearance: you had to fix the libseccomp issue on your pi4 or did you have to do the updates inside the container?

**Comment by cleggton** [comment]
To be clear.  The update needed to be applied to host machine.  I.e. the pi.   It seems a problem on older distros
