### ISSUE TITLE
rootless container - " failed open com status: (-3), path: "

### ISSUE THREAD

**Issue by Knapoc** [deconz-community/deconz-docker#109]
Hello all!

Currently I'm trying to move my setup from docker to podman and rootless containers.

This is my podman run command:
```bash
podman run --name=deconz \
  --rm \
  -p 8080:8080 -p 8443:8443 -p 5901:5901 \
  -v "/srv/deconz:/opt/deCONZ" \
  -v "/etc/localtime:/etc/localtime:ro" \
  -v "/home/user/deconz-otau:/root/otau" \
  -e "DECONZ_WEB_PORT=8080" \
  -e "DECONZ_WS_PORT=8443" \
  -e "DECONZ_VNC_MODE=1" \
  -e "DECONZ_VNC_PASSWORD=password" \
  -e "DECONZ_VNC_PORT=5901" \
  -e "DEBUG_INFO=1" \
  -e "DECONZ_UPNP=0" \
  -e "TZ=Europe/Vienna" \
  -e "DECONZ_DEVICE=/dev/ttyACM0" \
  --device "/dev/ttyACM0:/dev/ttyACM0" \
  --net slirp4netns:allow_host_loopback=true \
  --group-add=keep-groups \
  ghcr.io/deconz-community/deconz-docker:stable
```

When running it, it seems that deConz has issues to talk to the device which can be observed in the logs:
```
13:48:19:165 COM: /dev/ttyACM0 :  (0x1CF1/0x0030)
13:48:19:166 COM: /dev/ttyACM0 / serialno: , ConBee II
13:48:19:172 failed open com status: (-3), path: /dev/ttyACM0
13:48:20:153 wait reconnect 5 seconds
13:48:20:166 COM: /dev/ttyACM0 :  (0x1CF1/0x0030)
13:48:20:166 COM: /dev/ttyACM0 / serialno: , ConBee II
13:48:21:154 wait reconnect 4 seconds
13:48:21:653 networkState: CC_ReconnectNetwork
13:48:21:653 start reconnect to network
```

Both users (root & deconz) have access to the device from within the container:
```
$ podman exec --user deconz -it deconz stty -a -F /dev/ttyACM0
speed 9600 baud; rows 0; columns 0; line = 0;
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>; eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R; werase = ^W; lnext = ^V;
discard = ^O; min = 1; time = 0;
-parenb -parodd -cmspar cs8 hupcl -cstopb cread clocal -crtscts
-ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl ixon -ixoff -iuclc -ixany -imaxbel -iutf8
opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
isig icanon iexten echo echoe echok -echonl -noflsh -xcase -tostop -echoprt echoctl echoke -flusho -extproc
```

What I tried so far:

- different images: not working
- running the container in rootful mode: working
- adding all capabilities: same error as above
- add privileged flag: getting error of `dev can't create file: /dev/ttyACM0 via mknod (missing permissions)`
- running with UID & GID 0: no success/same error
- Turn off label separation for the container: no success/same error

I'm thankful for any hints.

**Comment by Jo-Be-Co** [comment]
`deCONZ` is started with `gosu deconz /usr/bin/deCONZ $DECONZ_OPTS` - so maybe you check your device access by adding `gosu deconz` in front of `stty`.

**Comment by Knapoc** [comment]
Ah thanks for the hint. It seems gosu is the "culprit" since I get a permission denied with running it like that. I'll dig into it.

**Comment by Knapoc** [comment]
So I finally solved the issue by mounting a customer `start.sh`-script where I changed the command to run deconz with the following `exec setpriv --reuid=1000 --regid=1000 --keep-groups /usr/bin/deCONZ $DECONZ_OPTS`. The option `--keep-groups` made the difference for me.

I tried to accomplish the same with gosu but I didn't get it to work. According to [this comment](https://github.com/tianon/gosu/issues/33#issuecomment-283184609) gosu should inherit the groups but even specifying the group `dialout` I got a permission denied error.

I'll leave this issue open for now, since there may be a more elegant solution which can be implemented in the image.

**Comment by senilio** [comment]
Thanks a lot for that feedback. I'm closing the issue now but will use your findings.

**Comment by scottsweb** [comment]
@Knapoc would you be able to share the custom script and detail how you spun up the container. I am trying to get this container working with rootless podman too.

**Comment by Knapoc** [comment]
@scottsweb I just changed [this line](https://github.com/deconz-community/deconz-docker/blob/d8663c8dd20daba8f84ffd8442406957bddb25a6/docker/root/start.sh#L157) with the mentioned command, mounted it into the container and used it as the entrypoint.

**Comment by scottsweb** [comment]
@Knapoc thanks, neat trick! I will give it a try.

**Comment by scottsweb** [comment]
Haven't been able to get this to work yet. Here is what I am running (with the modified `start.sh`).

```
podman run --name=deconz \
  --rm \
  -p 8020:8020 -p 4043:4043 \
  -v "./data/deconz/start.sh:/start.sh:ro,z" \
  -v "./data/deconz:/opt/deCONZ:z" \
  -e "DECONZ_WEB_PORT=8080" \
  -e "DECONZ_WS_PORT=4043" \
  -e "DEBUG_INFO=1" \
  -e "TZ=Europe/Stockcholm" \
  -e "DECONZ_UID=1000" \
  -e "DECONZ_GID=1000" \
  -e "DECONZ_DEVICE=/dev/ttyACM0" \
  --device "/dev/ttyACM0:/dev/ttyACM0" \
  --net slirp4netns:allow_host_loopback=true \
  --group-add=keep-groups \
  deconzcommunity/deconz:stable
```

Unfortunately it still looks like I am unable to connect to the device:

```
12:28:13:184 Announced to internet https://phoscon.de/discover
12:28:14:316 COM: /dev/ttyACM0 / serialno: , ConBee II
12:28:15:316 COM: /dev/ttyACM0 / serialno: , ConBee II
12:28:15:851 DEV Tick.Init: booted after 8000 seconds
12:28:19:316 COM: /dev/ttyACM0 / serialno: , ConBee II
12:28:20:315 COM: /dev/ttyACM0 / serialno: , ConBee II
12:28:22:806 GW update firmware found: /usr/share/deCONZ/firmware/deCONZ_ConBeeII_0x26720700.bin.GCF
12:28:24:317 COM: /dev/ttyACM0 / serialno: , ConBee II
12:28:25:315 COM: /dev/ttyACM0 / serialno: , ConBee II
12:28:28:284 start reconnect to network
12:28:29:314 COM: /dev/ttyACM0 / serialno: , ConBee II
12:28:30:314 COM: /dev/ttyACM0 / serialno: , ConBee II
12:28:33:534 failed to reconnect to network try=1
12:28:34:314 COM: /dev/ttyACM0 / serialno: , ConBee II
12:28:35:315 COM: /dev/ttyACM0 / serialno: , ConBee II
```

**Comment by sfhl** [comment]
> `exec setpriv --reuid=$DECONZ_UID --regid=$DECONZ_GID --keep-groups /usr/bin/deCONZ $DECONZ_OPTS`. The option `--keep-groups`



> So I finally solved the issue by mounting a custom `start.sh`-script where I changed the command to run deconz with the following `exec setpriv --reuid=$DECONZ_UID --regid=$DECONZ_GID --keep-groups /usr/bin/deCONZ $DECONZ_OPTS`. The option `--keep-groups` made the difference for me.
> 
> I tried to accomplish the same with gosu but I didn't get it to work. According to [this comment](https://github.com/tianon/gosu/issues/33#issuecomment-283184609) gosu should inherit the groups but even specifying the group `dialout` I got a permission denied error.
> 
> I'll leave this issue open for now, since there may be a more elegant solution which can be implemented in the image.

got the same problem today and the workaround is still needed and working. thank you!

**Comment by phdelodder** [comment]
@sfhl a PR is welcome.
