### ISSUE TITLE
websocket problems in non-host mode

### ISSUE THREAD

**Issue by rubinho76** [deconz-community/deconz-docker#116]
hello guys

i have switched deconz to docker.
Then I had problems with the websocket connection.
Even though I entered the following parameters, I could not log in to the website. The website went up but the login always failed
    environment:
      - DECONZ_WEB_PORT=81
      - DECONZ_WS_PORT=8443
    ports: 
      - 81:81
      - 8443:8443
Only after I set to "network_mode: host" it was possible to log in.

I suspect due to the NAT in the Docker container there is an error in the communication.
Can anyone confirm the problem?

**Comment by senilio** [comment]
This is a general docker question likely unrelated to deCONZ... and it's stale.
