### ISSUE TITLE
VNC Crash Docker/ Synology DECONZ_VNC_MODE 1

### ISSUE THREAD

**Issue by laurent941** [deconz-community/deconz-docker#117]
hello 

since the migration from deconz/marthoc to deconz community/deconz docker ( synology ) crashes when you activate VNC with DECONZ_VNC_MODE 1
I thought it would be fixed with the last updates but it's still not the case 
any tip to fix the problem ?

thank you in advance

**Comment by exi** [comment]
Can confirm, i just moved from marthoc to community/deconz-docker and get this error:
```
tigervncserver: No VNC server running for this user!
TigerVNC server sessions:
X DISPLAY #     RFB PORT #      PROCESS ID      SERVER
/usr/bin/xauth:  file /home/deconz/.Xauthority does not exist
Killing Xtigervnc process ID 46... which seems to be deadlocked. Using SIGKILL!
=================== tail /home/deconz/.vnc/sensorpi.fritz.box:5900.log ===================
================================================================================
==========
tigervncserver: /usr/bin/Xtigervnc did not start up, please look into '/home/deconz/.vnc/sensorpi.fritz.box:5900.log' to determine the reason! -1
```

The mentioned log file is always empty.

**Comment by exi** [comment]
I managed to run ```gosu deconz tigervncserver -SecurityTypes VncAuth,TLSVnc :0 -verbose -dry-run ``` in the container with this result:

```
=================== tail /home/deconz/.vnc/sensorpi.fritz.box:5900.log ===================
sleep: cannot read realtime clock: Operation not permitted
==========================================================================================
```

This seems to be an issue with the list of allowed syscalls in docker.
Running the container with ```--privileged``` makes it work!

**Comment by senilio** [comment]
@laurent941 pls confirm if your issue is fixed by running privileged

If not, i suggest deleting the vnc folder in the deconz volume. It will be recreated on the next container start.
