### ISSUE TITLE
deconz cant connect to Raspbee on RPi4

### ISSUE THREAD

**Issue by TheIgnitedWizard** [deconz-community/deconz-docker#119]
Hi, 
I am trying to get my Raspbee running with the Deconz Container.
When booting up I see this in the Gateway-options:
<img width="312" alt="Bildschirmfoto 2022-06-02 um 21 06 16" src="https://user-images.githubusercontent.com/31147442/171717542-f6071b6d-9816-4316-8aef-0b33366d2bcc.png">
It seems that it recognizes the Raspbee, but cant connect?
Configuration is:

docker run -d \
    --name=deconz \
    --restart=always \
    -p 80:80 \
    -p 443:443 \
    -v /etc/localtime:/etc/localtime:ro \
    -v /opt/deconz:/opt/deCONZ \
    --device=/dev/ttyS0 \
-e DECONZ_DEVICE=/dev/ttyS0 \
-e DECONZ_VNC_MODE=1 \
-e DECONZ_VNC_PORT=5900 \
-e DECONZ_VNC_PASSWORD=changeme \
    deconzcommunity/deconz

logs are here: 
https://pastebin.com/80P6BS0G

I noticed it uses /dev/ttyAMA0 even if I set it to /dev/ttyS0/

here is a list of my /dev/tty*
https://pastebin.com/rejAjat1

I am new to Docker but I wanted to use it as my old deconz distro died and I want to install HomeAssistant via docker with it.
WiringPI is on the newest version.
Using a Raspberry Pi 4
Serial is enabled and dt-overlay=disable-bt in config.txt
Thanks for your help

**Comment by wmn79** [comment]
You can try to add:
--privileged

in your configuration. See also #118 .

**Comment by TheIgnitedWizard** [comment]
> You can try to add: --privileged
> 
> in your configuration. See also #118 .

Unfortunately this didnt work out. Raspbee worked fine on the phoscon Rpi Image.

**Comment by wmn79** [comment]
Do you have wiringpi installed? I see it is a prerequisite for a Raspbee on a PI4. From the readme.md under Pre-requisites:

For a RaspBee/Raspbee 2 installation on a Raspberry PI 4B : Make sure to have Wiring Pi updated to the latest version! Install instructions can be found on http://wiringpi.com/wiringpi-updated-to-2-52-for-the-raspberry-pi-4b/_

**Comment by TheIgnitedWizard** [comment]
Yes it is installed and gpio -v is working too

**Comment by TheIgnitedWizard** [comment]
I also added pi to dialout and tried to run it as pi and root

**Comment by volschin** [comment]
But your /dev/ttyAMA01 is not in the dialout group. This should be normal behaviour.

**Comment by TheIgnitedWizard** [comment]
How do I change this?

**Comment by volschin** [comment]
Not sure. I only see that differs.

**Comment by TheIgnitedWizard** [comment]
> 

still not working, unfortunately.
I cant access ls -al /dev/serial/by-id/ as the directory doesnt exist

**Comment by senilio** [comment]
Try installing package linux-modules-extra-raspi, then reboot

**Comment by TheIgnitedWizard** [comment]
> Try installing package linux-modules-extra-raspi, then reboot

how do i do this? Sorry I am quite new to Docker and going this deep on RPi, normally I install my package or run my script and everythings fine

**Comment by senilio** [comment]
I recommend booting your pi on the official SD card image, and then perform the raspbee firmware fishing from there according to the instructions on the GitHub wiki.

https://phoscon.de/en/raspbee2/sdcard

**Comment by cwildfoerster** [comment]
hi, ran into the same problem after migrating from a rpi2 to rpi4 using docker, didn't read the readme completly, fixed the problem without needing to run as root:
https://github.com/deconz-community/deconz-docker#configuring-raspbian-for-raspbee

**Comment by senilio** [comment]
Stale
