### ISSUE TITLE
Not able to login after migration

### ISSUE THREAD

**Issue by knudsvik** [deconz-community/deconz-docker#120]
I finally migrated from the `marthoc/deconz` image today. After pulling the new image and changing my docker compose config as instructed in the readme, my Phoscon now says Login failed when using the same password as before. Not possible to reset password either due to 10min conflict (even right after rebooting my system).

My Home Assistant instance can not connect to DeConz anymore either, getting this error in the log: `Error connecting to deCONZ gateway at xx.xxx.xxx.xx` (where xx. is the IP address).

**Comment by phdelodder** [comment]
Can you try to restore a backup?

**Comment by knudsvik** [comment]
Loading backup failed ... :(
