### ISSUE TITLE
after update to 2.17.0 no gateway information

### ISSUE THREAD

**Issue by canedje** [deconz-community/deconz-docker#122]
Affter update to 2.17.0 gateway showing no information.
The selected language is englisch but page showing german information. Both pages showing no information.
The rest of the docker is working fine. light, switches and sensors showing up normal
Running docker under latest unraid.
![image](https://user-images.githubusercontent.com/23150947/172670822-388661d7-ac4c-4da6-9709-74256b389112.png)
VNC is also working fine

**Comment by senilio** [comment]
Not related to docker. Clear browser cache and retry.

**Comment by canedje** [comment]
That was the trick thanks
