### ISSUE TITLE
Error 413 when calling phoscon

### ISSUE THREAD

**Issue by bvelte95** [deconz-community/deconz-docker#123]
I am running the deconz docker on Unraid. A year ago everything worked out fine, but now I am not able to reach the GUI anymore, as it only gives me Error 413. Is this known or happening to anyone else?

**Comment by senilio** [comment]
https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Debugging-101

Start with providing useful information :)

**Comment by bvelte95** [comment]
I just recognized it solved itself and had something to do with the browser'a cache or cookies.
