### ISSUE TITLE
Container loses gateway info after update

### ISSUE THREAD

**Issue by UkeHa** [deconz-community/deconz-docker#128]
I migrated from the old [docker](https://github.com/marthoc/docker-deconz) to this version. Every time i update this container, my gateway (called Phoscon) is lost and a new Phoscon-GW i being created. I'm being asked to create a new password and add my lights. I then import a backup of my old gateway and keep using that. This works until the next update.

I don't want to transfer my lights to the new gateway and don't know if the problem would persist once i add all the lights to the new gateway, as i'd prefer to keep all my lights and automations as is and not have to add 60+ lights and sensors as well as my automations.

Is there a way to persist my gateway info or do i need to transfer my lights to the new gateway (once)?

I'm running Docker in Unraid (latest) on firmware 26720700 and Version 2.17.01 / 1.7.2022.

**Comment by senilio** [comment]
You must keep /opt/deCONZ on persistent storage, otherwise the files are lost on container recreation/upgrade.

Note that the mount point changed from the marthoc container.

**Comment by UkeHa** [comment]
i changed the previous config folder in docker from /root/.local/share/dresden-elektronik/deCONZ and /opt/deCONZ. I'll check back if this persists after the next update!
