### ISSUE TITLE
Latest (2.17.01) deconz UI Gateway screen missing info, wrong language displayed

### ISSUE THREAD

**Issue by smuskiew** [deconz-community/deconz-docker#131]
I just pulled the latest (2.17.01) deconz container image, all appears to be working except that I noticed in the UI the "Gateway" screen appears to be empty (no SW/FW versions or any other info that is normally shown on this page are displayed).  Also the language at the devices at the bottom isn't displaying in my selected view language (English).

Here's what the Gateway screen looks like for me with 2.17.01
<img width="1323" alt="Screen Shot 2022-07-24 at 11 37 56 AM" src="https://user-images.githubusercontent.com/37269491/180655116-02105be3-e45a-404e-8c9c-dfb52166e18d.png">

This does appear to be mainly cosmetic, the device control screens and API are working as expected. 

Just thought you should be aware of this, thanks!

**Comment by eikroGit** [comment]
Just clear browser's cache. Had the same issue right after update

**Comment by senilio** [comment]
Unrelated to docker
