### ISSUE TITLE
Unable to load backup.

### ISSUE THREAD

**Issue by Stubbs** [deconz-community/deconz-docker#134]
I've just switched from the old marthoc docker image, and as instructed by the migration guide I took a backup of the config.

Now I have the new version up and running I can't import the config, I just get an error "Loading backup failed" and there's nothing in the log to indicate what happened.

Version  is 2.18.0 / 07/08/2022 and firmware 26660700

**Comment by senilio** [comment]
TBH there's no reason to restore the backup as long as you mount the old files in /opt/deCONZ. Failure to restore backup is likely not related to docker though. I'd try the forums at https://forum.phoscon.de/
