### ISSUE TITLE
High CPU usage after last pull

### ISSUE THREAD

**Issue by ktpx** [deconz-community/deconz-docker#136]
After pulling the latest, the deconz bin is taking a lot of cpu time (180%) on my PI4/4gig.  This was not an issue on the previous build 
i ran. Not sure whats going on there.... Conbee II USB.  The log
doesn't a whole lot going.

**Comment by phdelodder** [comment]
The container hasn't changed, I would report it to deconz it self.

**Comment by ktpx** [comment]
> The container hasn't changed, I would report it to deconz it self.

Ok, yeah, lmust be their binary eating the resources, not a lot of debug tools in the container.  Will contact deconz.
thx
