### ISSUE TITLE
Unable to fully start deCONZ

### ISSUE THREAD

**Issue by xconverge** [deconz-community/deconz-docker#14]
This image (2.13.02 latest image) connects to my conbee II and gets the right SN, but then fails to move past that and stays in limbo for...ever?

[2.13.02 image log](https://github.com/deconz-community/deconz-docker/files/7536500/_deconz_logs.txt)

Gets stuck in a loop:

```

22:24:02:479 start reconnect to network


22:24:02:546 COM: /dev/ttyACM0 / serialno: DE2250384, ConBee II


22:24:06:546 COM: /dev/ttyACM0 / serialno: DE2250384, ConBee II


22:24:07:479 failed to reconnect to network try=1


22:24:07:546 COM: /dev/ttyACM0 / serialno: DE2250384, ConBee II


22:24:11:546 COM: /dev/ttyACM0 / serialno: DE2250384, ConBee II


22:24:12:479 failed to reconnect to network try=2


22:24:12:545 COM: /dev/ttyACM0 / serialno: DE2250384, ConBee II


22:24:16:545 COM: /dev/ttyACM0 / serialno: DE2250384, ConBee II


22:24:17:478 failed to reconnect to network try=3


22:24:17:546 COM: /dev/ttyACM0 / serialno: DE2250384, ConBee II


22:24:21:547 COM: /dev/ttyACM0 / serialno: DE2250384, ConBee II


22:24:22:479 failed to reconnect to network try=4


22:24:22:548 COM: /dev/ttyACM0 / serialno: DE2250384, ConBee II


22:24:26:547 COM: /dev/ttyACM0 / serialno: DE2250384, ConBee II


22:24:27:479 failed to reconnect to network try=5


22:24:27:547 COM: /dev/ttyACM0 / serialno: DE2250384, ConBee II


22:24:31:546 COM: /dev/ttyACM0 / serialno: DE2250384, ConBee II


22:24:32:479 failed to reconnect to network try=6


22:24:32:548 COM: /dev/ttyACM0 / serialno: DE2250384, ConBee II


22:24:36:546 COM: /dev/ttyACM0 / serialno: DE2250384, ConBee II


22:24:37:479 failed to reconnect to network try=7


22:24:37:547 COM: /dev/ttyACM0 / serialno: DE2250384, ConBee II


22:24:41:545 COM: /dev/ttyACM0 / serialno: DE2250384, ConBee II


22:24:42:479 failed to reconnect to network try=8


22:24:42:546 COM: /dev/ttyACM0 / serialno: DE2250384, ConBee II


22:24:46:547 COM: /dev/ttyACM0 / serialno: DE2250384, ConBee II


22:24:47:479 failed to reconnect to network try=9


22:24:47:546 COM: /dev/ttyACM0 / serialno: DE2250384, ConBee II


22:24:51:546 COM: /dev/ttyACM0 / serialno: DE2250384, ConBee II


22:24:52:479 failed to reconnect to network try=10


22:24:52:547 COM: /dev/ttyACM0 / serialno: DE2250384, ConBee II


22:24:56:545 COM: /dev/ttyACM0 / serialno: DE2250384, ConBee II


22:24:57:479 reconnect network failed, try later
```

@phdelodder was nice enough to make me a 2.13.01 image as well to test but the problem persisted there.
[2.13.01 image log](https://github.com/deconz-community/deconz-docker/files/7536499/_deconz_logs.1.txt)

here is a snippet from the marthoc 2.13.01 image to show the SN matches and the FW version:

```22:32:31:649 GW firmware version is up to date: 0x26700700,
22:32:31:649 GW update firmware found: /usr/share/deCONZ/firmware/deCONZ_ConBeeII_0x26660700.bin.GCF,
22:32:29:598 Device firmware version 0x26700700 ConBee II,
22:32:27:739 COM: /dev/ttyACM0 / serialno: DE2250384, ConBee II,
22:32:28:505 Skip idle timer callback, too early: elapsed 949 msec
```

Here is my docker compose:

```
deconz:
        container_name: deconz
        image: deconzcommunity/deconz:latest
        environment:
            - DECONZ_UID=1000
            - DECONZ_GID=1000
            - TZ=${TZ}
            - DECONZ_DEVICE=/dev/ttyACM0
            - DECONZ_WEB_PORT=80
            - DECONZ_WS_PORT=443
            - DEBUG_INFO=1
            - DEBUG_APS=0
            - DEBUG_ZCL=0
            - DEBUG_ZDP=0
            - DEBUG_OTAU=0
            - DECONZ_VNC_PASSWORD=${DECONZ_VNC_PASSWORD}
            - DECONZ_VNC_MODE=1
            - DECONZ_VNC_PORT=5900
            - DECONZ_NOVNC_PORT=6080
            - DECONZ_START_VERBOSE=1
        volumes:
            - '${DOCKER_VOLUMES}/deconz_new:/opt/deCONZ'
        devices:
            - /dev/ttyACM0
        ports:
            - 8087:80
            - 8044:443
            - 8900:5900
            - 8901:6080
        restart: always
```

Here is my diff in migrating from marthoc to this image:

```diff
diff --git a/docker-compose.yml b/docker-compose.yml
index 27c3b14..69c2198 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -291,12 +291,12 @@ services:

     deconz:
         container_name: deconz
-        image: marthoc/deconz:latest
+        image: deconzcommunity/deconz:latest
         # labels:
         #     com.centurylinklabs.watchtower.enable: false
         environment:
-            - PUID=${PUID}
-            - PGID=${PGID}
+            - DECONZ_UID=1000
+            - DECONZ_GID=1000
             - TZ=${TZ}
             - DECONZ_DEVICE=/dev/ttyACM0
             - DECONZ_WEB_PORT=80
@@ -310,8 +310,9 @@ services:
             - DECONZ_VNC_MODE=1
             - DECONZ_VNC_PORT=5900
             - DECONZ_NOVNC_PORT=6080
+            - DECONZ_START_VERBOSE=1
         volumes:
-            - '${DOCKER_VOLUMES}/deconz:/root/.local/share/dresden-elektronik/deCONZ'
+            - '${DOCKER_VOLUMES}/deconz_new:/opt/deCONZ'
         devices:
             - /dev/ttyACM0
         ports:
```

I tried "privileged: true" with no change in behavior. I tried different UID and GIDs. I also tried the original volume that I was using with the marthoc image as well but no difference so stayed with trying to bring up a clean new setup with this image. This is running on a synology NAS with an extension cable, no HW changes between attempting to migrate between images.

**Comment by senilio** [comment]
Could you just check the permissions on the device inside the container, plus the permissions on the user?

```
docker exec -it deconz id 1000
docker exec -it deconz ls -al /dev
```

**Comment by senilio** [comment]
@mhoogenbosch Migration instructions will be added shortly :)

**Comment by mhoogenbosch** [comment]
> @mhoogenbosch Migration instructions will be added shortly :)

So if I understand correctly this is expectec behavior? Great! Good to know. Will hold my patience then.

**Comment by Mimiix** [comment]
@xconverge  Can you add some longer logs? Typically, you'll get a "reason" line in the logs when joining the net takes a while.

**Comment by senilio** [comment]
@mhoogenbosch Instructions added to the top of the repo readme.

**Comment by mhoogenbosch** [comment]
> @mhoogenbosch Instructions added to the top of the repo readme. Feel free to reach out on discord or start a new issue if you continue to have issues.

works great! tnx

**Comment by xconverge** [comment]
@senilio

```
sudo docker exec -it deconz id 1000
uid=1000(deconz) gid=1000(deconz) groups=1000(deconz),0(root)


sudo docker exec -it deconz ls -al /dev/ttyACM0
crw------- 1 root root 166, 0 Nov 15 09:08 /dev/ttyACM0
```

**Comment by xconverge** [comment]
@Mimiix not seeing any reasons even when left longer
[_deconz_logs.txt](https://github.com/deconz-community/deconz-docker/files/7540451/_deconz_logs.txt)

**Comment by Mimiix** [comment]
What debug flags are used?

**Comment by senilio** [comment]
> ```
> sudo docker exec -it deconz id 1000
> uid=1000(deconz) gid=1000(deconz) groups=1000(deconz),0(root)
> 
> 
> sudo docker exec -it deconz ls -al /dev/ttyACM0
> crw------- 1 root root 166, 0 Nov 15 09:08 /dev/ttyACM0
> ```

So... only user root have permissions on your device. Your pi user is a member of the root group, but that does not grant access given that the device permissions are 600.

**Comment by senilio** [comment]
I wonder what happened to the dialout group as defined here https://github.com/deconz-community/deconz-docker/blob/main/docker/Dockerfile#L76-L77

**Comment by xconverge** [comment]
> 
> 
> What debug flags are used?

All flags are in the initial post with the docker compose

**Comment by mhoogenbosch** [comment]
> I've the same Error. Cause i'm only using the Synology NAS as docker-platform i have no clue how to change the mountpoint of the container. Can anybody help me with that?

With a synology it is much easier, you can edit the folder when the container is turned of through the GUI.

**Comment by Mimiix** [comment]
Can you put error, APS and info on 2?

**Comment by xconverge** [comment]
> 
> 
> Can you put error, APS and info on 2?
[_deconz_logs.txt](https://github.com/deconz-community/deconz-docker/files/7540630/_deconz_logs.txt)

**Comment by Mimiix** [comment]
Okay, has to do with usb permissions.

09:43:23:216 failed open com status: (-3), path: /dev/ttyACM0

**Comment by digi303** [comment]
> > I've the same Error. Cause i'm only using the Synology NAS as docker-platform i have no clue how to change the mountpoint of the container. Can anybody help me with that?
> 
> With a synology it is much easier, you can edit the folder when the container is turned of through the GUI.

yes, I know the possibility to change data via the GUI. I just don't know what I have to enter where. I do have the option of specifying volumes, but I don't see a folder /opt/...

**Comment by mhoogenbosch** [comment]
> > > I've the same Error. Cause i'm only using the Synology NAS as docker-platform i have no clue how to change the mountpoint of the container. Can anybody help me with that?
> > 
> > 
> > With a synology it is much easier, you can edit the folder when the container is turned of through the GUI.
> 
> yes, I know the possibility to change data via the GUI. I just don't know what I have to enter where. I do have the option of specifying volumes, but I don't see a folder /opt/...

The opt folder is inside of the container. You need to link the/volume1/ folder with this opt folder. Maybe we should create a different issue for this.

**Comment by phdelodder** [comment]
I'm working on a fix with @xconverge, should be available later today

**Comment by xconverge** [comment]
Thanks @phdelodder, @senilio, and @Mimiix for the help #20 fixed this issue for my synology

**Comment by mcormick** [comment]
I'm still getting
> 19:23:37:884 failed open com status: (-3), path: /dev/ttyACM0

on this container on my Synology (DSM 6.2.4) while:

> docker pull deconzcommunity/deconz:latest
> latest: Pulling from deconzcommunity/deconz
> Digest: sha256:2dc49e8ac6320d2dd11fbe1f5a43e3fa6d6b038953e698bf189926598d9d3a93
> Status: Image is up to date for deconzcommunity/deconz:latest

I'm running the container with "High privilege".

**Comment by xconverge** [comment]
delete your container and image and repull

I am on sha256:a5e5341f77370db03eb34614ca97ecae65b53c952238e89977cff752bff9270e

**Comment by xconverge** [comment]
@mcormick were you able to get rolling?

**Comment by mcormick** [comment]
> @mcormick were you able to get rolling?

Actually I did not. I managed to pull https://registry.hub.docker.com/layers/deconzcommunity/deconz/latest/images/sha256-5eac961a92066fbe564125153c1a69eb993af5c0004a246a3b32c991aa8763e0 and ran that container, but I still get 
`failed open com status: (-3), path: /dev/ttyACM0`

Logs: [deCONZ-community_dsmDocker.csv.log](https://github.com/deconz-community/deconz-docker/files/7544091/deCONZ-community_dsmDocker.csv.log)

```
ash-4.3# sudo docker exec -it deCONZ-community id 1000
uid=1000(deconz) gid=1000(deconz) groups=1000(deconz),0(root)
ash-4.3# sudo docker exec -it deCONZ-community ls -al /dev/ttyACM0
crw------- 1 root root 166, 0 Nov 16 07:20 /dev/ttyACM0
```

**Comment by mcormick** [comment]
OK, So when I manually enter `sudo chmod g+rw /dev/ttyACM0` in the container terminal, it starts to work. Just not working on container start in `start.sh`.

**Comment by phdelodder** [comment]
@mcormick please create a different ticket.
With enabled '-e DECONZ_START_VERBOSE=1' logging
