### ISSUE TITLE
Cannot login after update from 2.14.01 to 2.18.02

### ISSUE THREAD

**Issue by Qaldak** [deconz-community/deconz-docker#144]
Hi 
I run my deconz-docker a long time ago. Actually I run it with v2.14.01 on a Raspberry Pi 3b (OS: Raspbian stretch). It runs without any issues.
After update to 2.17.01 (few weeks ago) and now to 2.18.02, I can not login anymore.

Docker logs:
`[deconzcommunity/deconz] Starting deCONZ...
[deconzcommunity/deconz] Current deCONZ version: 2.18.02
[deconzcommunity/deconz] Web UI port: 80
[deconzcommunity/deconz] Websockets port: 443
[deconzcommunity/deconz] Using options --auto-connect=1 --appdata=/opt/deCONZ --dbg-info=1 --dbg-aps=0 --dbg-zcl=0 --dbg-ddf=0 --dbg-dev=0 --dbg-zdp=0 --dbg-ota=0 --dbg-error=0 --dbg-http=0 --http-port=80 --ws-port=443
[deconzcommunity/deconz] Modifying user and group ID
[deconzcommunity/deconz] Checking device group ID
[deconzcommunity/deconz] VNC Disabled
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-deconz'
libpng warning: iCCP: known incorrect sRGB profile
QProcess: Destroyed while process ("/usr/bin/timedatectl") is still running.
This plugin does not support propagateSizeHints()
This plugin does not support propagateSizeHints()`

In dev tools (chrome) I see following error while GET: 
`<html><head></head><body><h1>This is not the page you are looking for</h1><p>The file /api/config couldn't be found.</p></body></html>`

to start I use docker-compose. .yml is according example on docker.hub.

Where is the problem and how can I solve it? Any inputs?

**Comment by phdelodder** [comment]
Can you try a hard refresh or an incognito page?

**Comment by Qaldak** [comment]
That's it. Using other devices or clearing cache works. I tought I had cleared the cache when I opened the dev tools. Thanks.
