### ISSUE TITLE
Disable noVNC password?

### ISSUE THREAD

**Issue by mani76** [deconz-community/deconz-docker#147]
There is parameter for defining vnc password:
DECONZ_VNC_PASSWORD

Is there possibility to disable password authentication and log in directly to noVnc?

**Comment by phdelodder** [comment]
Thanks for the suggestion!

I have created PR #148, if you want you can test it!

**Comment by mani76** [comment]
Tested using dev image with the following urls:
vnc.html
vnc_auto.html
vnc_lite.html

With and without passwords.
Both cases seem to work ok.

Thanks

**Comment by phdelodder** [comment]
I'll leave the PR open for 2 weeks and then I'll merge it.

**Comment by senilio** [comment]
@phdelodder Are we good to merge this?

**Comment by phdelodder** [comment]
Trigger a new workflow, lets see how it goes

**Comment by phdelodder** [comment]
Merged #148
