### ISSUE TITLE
Support listening on address 0.0.0.0 (IPv4) and ::/0 (IPv6)

### ISSUE THREAD

**Issue by martingruening** [deconz-community/deconz-docker#154]
I am using a dual stack IPv4/IPv6 docker environment.
By default deconz only binds to 0.0.0.0 and is therefore not reachable through IPv6.

Suggested change: also bind to ::/0 to support IPv6 connectivity.

**Comment by senilio** [comment]
There is currently no support for ipv6 in deCONZ. The deCONZ devs are planning to implement support beginning of next year, and once that happens this Docker image will get it as well.

**Comment by DZ945brH** [comment]
https://github.com/deconz-community/deconz-docker/issues/292

Reopen please. Deconz should support this by now.
