### ISSUE TITLE
Doesn't start after last update

### ISSUE THREAD

**Issue by giss69** [deconz-community/deconz-docker#157]
Hello,

after last update doesn't start anymore.
Hier is error in log:
`qt.qpa.xcb: could not connect to display :0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.`
downgrade to 2.19.2 work fine again.
What could be the problem with the new update?

Thank you!

**Comment by moorboss** [comment]
THe wole Deconz application looks to be gone after the latest update, what happened? Zshark lloks to be the new application in this container... or has a merge gone wrong?

**Comment by Davst** [comment]
Yep.. someone def messed up it seems.

**Comment by senilio** [comment]
Indeed a mistake was made, and the deCONZ image was accidentally overwritten by the work-in-progress zshark image. I've manually triggered a rebuild of the deCONZ image, so if you pull the image again you should be back to normal.

**Comment by giss69** [comment]
thank you, it's working again!
