### ISSUE TITLE
1564: wiringPi is missing

### ISSUE THREAD

**Issue by skypeja** [deconz-community/deconz-docker#158]
Hi,
i'm trying to upgrade firmware on my RaspBeeII running on RPi 4B on Docker (IoT Stack). Step by step acording to manual on this github page, but I'm getting 1564 error over and over again...   And now my Deconz app says: Vendor: Unknown, Product: -, Version: 2.19.03/19.9.2022, Firmware: Not connected

I've already installed a wiringPi and it's propertly running.... I think...

`pi@docker:~ $ docker run -it --rm --entrypoint "/firmware-update.sh" --privilege                                                 d --cap-add=ALL -v /dev:/dev -v /lib/modules:/lib/modules -v /sys:/sys deconzcom                                                 munity/deconz
-------------------------------------------------------------------

             deconzcommunity/deconz Firmware Flashing Script

                       Version: 0.8

-------------------------------------------------------------------

Listing attached devices...

GCFFlasher V3_17 (c) dresden elektronik ingenieurtechnik gmbh
Path             | Vendor | Product | Serial     | Type
-----------------+--------+---------+------------+-------
/dev/ttyAMA0     | 0x0000 | 0x0000  |            | RaspBee

Enter the full device path, or press Enter now to exit.

Device path .: /dev/ttyAMA0

-------------------------------------------------------------------

Firmware available for flashing:
deCONZ_ConBeeII_0x26720700.bin.GCF
deCONZ_RaspBeeII_0x26720700.bin.GCF
deCONZ_Rpi_0x26400500.bin.GCF

Enter the firmware file name from above, including extension.
Alternatively, you may enter the name of a firmware file to download
from any of the following sources:
 - http://deconz.dresden-elektronik.de/deconz-firmware/         (stable)
 - http://deconz.dresden-elektronik.de/deconz-firmware/beta/    (beta)

If you wish to exit, just hit Enter.

Firmware file: deCONZ_RaspBeeII_0x26720700.bin.GCF

-------------------------------------------------------------------

Device path .: /dev/ttyAMA0
Firmware file: deCONZ_RaspBeeII_0x26720700.bin.GCF
Timeout .....: 60

Are the above values correct?
Enter Y to proceed, any other entry to exit: y

Flashing...

GCFFlasher V3_17 (c) dresden elektronik ingenieurtechnik gmbh
Reboot device /dev/ttyAMA0 (RaspBee)
deCONZ firmware version 26690700
slip put 0xC0
slip put 0x0B
slip put 0x02
slip put 0x00
slip put 0x0C
slip put 0x00
slip put 0x05
slip put 0x00
slip put 0x26
slip put 0x02
slip put 0x00
slip put 0x00
slip put 0x00
slip put 0xBA
slip put 0xFF
slip put 0xC0
slip put 0xC0
slip put 0x81
slip put 0x02
slip put 0x7D
slip put 0xFF
slip put 0xC0
slip put 0xC0
slip put 0x81
slip put 0x02
slip put 0x7D
slip put 0xFF
slip put 0xC0
Bootloader version 0x00030003, app crc: 0x93C2CD88
slip put 0xC0
slip put 0x81
slip put 0x03
slip put 0x83
slip put 0x81
slip put 0x02
slip put 0x00
slip put 0x00
slip put 0x50
slip put 0x00
slip put 0x00
slip put 0x1F
slip put 0xAA
slip put 0xAA
slip put 0xAA
slip put 0xAA
slip put 0x5F
slip put 0xFB
slip put 0xC0
Reboot device /dev/ttyAMA0 (RaspBee)
action: reset device RaspBee

1564: Error: (assert) wiringPi lib not installed

Flashing Error! Please re-run this script...

pi@docker:~ $`

`pi@docker:~ $ gpio -v
gpio version: 2.52
Copyright (c) 2012-2018 Gordon Henderson
This is free software with ABSOLUTELY NO WARRANTY.
For details type: gpio -warranty

Raspberry Pi Details:
  Type: Pi 4B, Revision: 05, Memory: 4096MB, Maker: Sony
  * Device tree is enabled.
  *--> Raspberry Pi 4 Model B Rev 1.5
  * This Raspberry Pi supports user-level GPIO access.
pi@docker:~ $ gpio readall
 +-----+-----+---------+------+---+---Pi 4B--+---+------+---------+-----+-----+
 | BCM | wPi |   Name  | Mode | V | Physical | V | Mode | Name    | wPi | BCM |
 +-----+-----+---------+------+---+----++----+---+------+---------+-----+-----+
 |     |     |    3.3v |      |   |  1 || 2  |   |      | 5v      |     |     |
 |   2 |   8 |   SDA.1 |   IN | 1 |  3 || 4  |   |      | 5v      |     |     |
 |   3 |   9 |   SCL.1 |   IN | 1 |  5 || 6  |   |      | 0v      |     |     |
 |   4 |   7 | GPIO. 7 |   IN | 1 |  7 || 8  | 1 | ALT0 | TxD     | 15  | 14  |
 |     |     |      0v |      |   |  9 || 10 | 1 | ALT0 | RxD     | 16  | 15  |
 |  17 |   0 | GPIO. 0 |   IN | 1 | 11 || 12 | 0 | IN   | GPIO. 1 | 1   | 18  |
 |  27 |   2 | GPIO. 2 |   IN | 0 | 13 || 14 |   |      | 0v      |     |     |
 |  22 |   3 | GPIO. 3 |   IN | 0 | 15 || 16 | 0 | IN   | GPIO. 4 | 4   | 23  |
 |     |     |    3.3v |      |   | 17 || 18 | 0 | IN   | GPIO. 5 | 5   | 24  |
 |  10 |  12 |    MOSI |   IN | 0 | 19 || 20 |   |      | 0v      |     |     |
 |   9 |  13 |    MISO |   IN | 0 | 21 || 22 | 0 | IN   | GPIO. 6 | 6   | 25  |
 |  11 |  14 |    SCLK |   IN | 0 | 23 || 24 | 1 | IN   | CE0     | 10  | 8   |
 |     |     |      0v |      |   | 25 || 26 | 1 | IN   | CE1     | 11  | 7   |
 |   0 |  30 |   SDA.0 |   IN | 1 | 27 || 28 | 1 | IN   | SCL.0   | 31  | 1   |
 |   5 |  21 | GPIO.21 |   IN | 1 | 29 || 30 |   |      | 0v      |     |     |
 |   6 |  22 | GPIO.22 |   IN | 1 | 31 || 32 | 0 | IN   | GPIO.26 | 26  | 12  |
 |  13 |  23 | GPIO.23 |   IN | 0 | 33 || 34 |   |      | 0v      |     |     |
 |  19 |  24 | GPIO.24 |   IN | 0 | 35 || 36 | 0 | IN   | GPIO.27 | 27  | 16  |
 |  26 |  25 | GPIO.25 |   IN | 0 | 37 || 38 | 0 | IN   | GPIO.28 | 28  | 20  |
 |     |     |      0v |      |   | 39 || 40 | 0 | IN   | GPIO.29 | 29  | 21  |
 +-----+-----+---------+------+---+----++----+---+------+---------+-----+-----+
 | BCM | wPi |   Name  | Mode | V | Physical | V | Mode | Name    | wPi | BCM |
 +-----+-----+---------+------+---+---Pi 4B--+---+------+---------+-----+-----+`

please can anybody help me?

**Comment by senilio** [comment]
There is a new flasher in development, and we expect it to ship with deCONZ "soon". When that's done, there won't be a need for wiringpi any more. See https://github.com/dresden-elektronik/gcfflasher

If you need to flash the Raspbee, you can download one of the official sd card images, boot your Raspberry Pi on that and run the included flasher from there. We will not include Wiringpi with this docker image.
