### ISSUE TITLE
Xiaomi Devices weird behaviour after Deconz Restart

### ISSUE THREAD

**Issue by marcor78** [deconz-community/deconz-docker#160]
Hello!
I recently migrated from marthoc/deconz to the community deconz image and I'm experiencing an odd behaviour from all my xiaomi devices.
My network is made with 17 xiaomi devices (multisensors, motion sensors and contact sensors) and a bunch of Ikea Tradfri devices (remotes, motion sensors, lights).
I use to reboot deconz every night on a cronjob and after every reboot - in the UI - ikea tradfri devices are immediately available and with their correct state, while xiaomi devices are all unavailable until their state changes (exmotion detected, temperature changes, etc). After the first xiaomi device is available again in the UI, slowly all other devices become available, but with a wrong state: all binary_sensors (ex. contact, motion) appear as "on" even if they're really off (door closed appear as open in Deconz UI).
In practice:
- 3am: deconz restarts on cronjob
- 4am: homeassistant restarts on cronjob
- 7am: I wake up and all the motion sensors are "on" and my front door appears as open, with a heart attack included

I tried everything:
- unpair-repair devices
- changed batteries
- reset devices through VNC
- repull docker image
Result: none of this changed the behaviour

Here's my setup:
Gateway: Conbee II (vers. 264A0700)
Deconz installation: docker image on VM in Proxmox

**Comment by phdelodder** [comment]
I don't think this is relevant to the docker, you should check with deconz it self.
