### ISSUE TITLE
Where to mount custom DDF files?

### ISSUE THREAD

**Issue by aradmidias** [deconz-community/deconz-docker#163]
I am having troubles identifying the correct folder to place custom DDF files in (Image Tag: `2.19.03`). Which is the folder _inside the Container_ where custom tailored DDF files must be placed for deCONZ to pick them up?

---

The Documentation states the following:
> All DDF provided directly with deCONZ typically reside in `/usr/share/deCONZ/devices/` on a Linux system and are loaded first. However, files residing in the home directory of the user running deCONZ (e.g. `/home/<DECONZUSER>/.local/share/dresden-elektronik/deCONZ/devices`) will override the pre-packaged files to allow users to amend and keep their own files if desired.

In my case, the user running `/usr/bin/deCONZ` is `deconz`. According to `/etc/passwd` that user's home directory is `/home/deconz/`

But placing either DDF from [this forum entry](https://forum.phoscon.de/t/my-ddf-blinds/1858/6) or that [Merge-Request](https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6110/files) (specifically [this file](https://raw.githubusercontent.com/dresden-elektronik/deconz-rest-plugin/d102ec19e2b227741c2818f2545e51c5c6156040/devices/vendor/fyrtur_block-out_roller_blind.json)) in `/home/deconz/.local/share/dresden-elektronik/deCONZ/devices` did not cause deCONZ to pick up that file:
```log
00:04:03:104 DEV no DDF for 0x000D6FFFFE2EE5B8, modelId: FYRTUR block-out roller blind
```

So I wrote a script to place the files in various locations. The following is a cross product from various potential home-locations, locations being relative to these home locations (found by piping `/usr/lib/libdeCONZ.so.1.2.0` through `strings`) and sub-folders from within these locations (just to be safe):
```bash
# Place the DDF in /my-ddf.json prior running this.
for d in /root/ /tmp/runtime-deconz/ /home/deconz/ /opt/deCONZ/ / ; do
   for p in .local/share/data/dresden-elektronik/deCONZ .local/share/deCONZ .local/share/dresden-elektronik/deCONZ ; do
      for z in / /devices/ /devices/vendor/ ; do
         mkdir -p ${d}${p}${z}
         cp -ar /my-ddf.json ${d}${p}${z}my-ddf.json
         chown -R deconz:deconz ${d}${p}
      done
   done
done
```

**Notes:**
* `/root/.local/share/dresden-elektronik/deCONZ/devices/my-ddf.json` is just one of multiple locations, that I tried prior to writing this script.
* Since the container is only stopped (but not deleted) when the deCONZ Desktop Application is quit (using `File` -> `Quit` or `CTRL+Q`) these modifications remain in the Container.
* The files within `/root/...` will not be picked up, even if the mode of `/root` is set to `766`

This results in 45 different locations, from which none is picked up:
```text
/root/.local/share/deCONZ/my-ddf.json
/root/.local/share/deCONZ/devices/my-ddf.json
/root/.local/share/deCONZ/devices/vendor/my-ddf.json
/root/.local/share/dresden-elektronik/deCONZ/my-ddf.json
/root/.local/share/dresden-elektronik/deCONZ/devices/my-ddf.json
/root/.local/share/dresden-elektronik/deCONZ/devices/vendor/my-ddf.json
/root/.local/share/data/dresden-elektronik/deCONZ/my-ddf.json
/root/.local/share/data/dresden-elektronik/deCONZ/devices/my-ddf.json
/root/.local/share/data/dresden-elektronik/deCONZ/devices/vendor/my-ddf.json
/tmp/runtime-deconz/.local/share/deCONZ/my-ddf.json
/tmp/runtime-deconz/.local/share/deCONZ/devices/my-ddf.json
/tmp/runtime-deconz/.local/share/deCONZ/devices/vendor/my-ddf.json
/tmp/runtime-deconz/.local/share/dresden-elektronik/deCONZ/my-ddf.json
/tmp/runtime-deconz/.local/share/dresden-elektronik/deCONZ/devices/my-ddf.json
/tmp/runtime-deconz/.local/share/dresden-elektronik/deCONZ/devices/vendor/my-ddf.json
/tmp/runtime-deconz/.local/share/data/dresden-elektronik/deCONZ/my-ddf.json
/tmp/runtime-deconz/.local/share/data/dresden-elektronik/deCONZ/devices/my-ddf.json
/tmp/runtime-deconz/.local/share/data/dresden-elektronik/deCONZ/devices/vendor/my-ddf.json
/home/deconz/.local/share/deCONZ/my-ddf.json
/home/deconz/.local/share/deCONZ/devices/my-ddf.json
/home/deconz/.local/share/deCONZ/devices/vendor/my-ddf.json
/home/deconz/.local/share/dresden-elektronik/deCONZ/my-ddf.json
/home/deconz/.local/share/dresden-elektronik/deCONZ/devices/my-ddf.json
/home/deconz/.local/share/dresden-elektronik/deCONZ/devices/vendor/my-ddf.json
/home/deconz/.local/share/data/dresden-elektronik/deCONZ/my-ddf.json
/home/deconz/.local/share/data/dresden-elektronik/deCONZ/devices/my-ddf.json
/home/deconz/.local/share/data/dresden-elektronik/deCONZ/devices/vendor/my-ddf.json
/opt/deCONZ/.local/share/deCONZ/my-ddf.json
/opt/deCONZ/.local/share/deCONZ/devices/my-ddf.json
/opt/deCONZ/.local/share/deCONZ/devices/vendor/my-ddf.json
/opt/deCONZ/.local/share/dresden-elektronik/deCONZ/my-ddf.json
/opt/deCONZ/.local/share/dresden-elektronik/deCONZ/devices/my-ddf.json
/opt/deCONZ/.local/share/dresden-elektronik/deCONZ/devices/vendor/my-ddf.json
/opt/deCONZ/.local/share/data/dresden-elektronik/deCONZ/my-ddf.json
/opt/deCONZ/.local/share/data/dresden-elektronik/deCONZ/devices/my-ddf.json
/opt/deCONZ/.local/share/data/dresden-elektronik/deCONZ/devices/vendor/my-ddf.json
/.local/share/deCONZ/my-ddf.json
/.local/share/deCONZ/devices/my-ddf.json
/.local/share/deCONZ/devices/vendor/my-ddf.json
/.local/share/dresden-elektronik/deCONZ/my-ddf.json
/.local/share/dresden-elektronik/deCONZ/devices/my-ddf.json
/.local/share/dresden-elektronik/deCONZ/devices/vendor/my-ddf.json
/.local/share/data/dresden-elektronik/deCONZ/my-ddf.json
/.local/share/data/dresden-elektronik/deCONZ/devices/my-ddf.json
/.local/share/data/dresden-elektronik/deCONZ/devices/vendor/my-ddf.json
```

The only location, that **is** being picked up, is underneath `/usr/share/deCONZ/devices/`, but that is neither persisted upon the Container's recreation, nor intended for storing custom DDF files:
```log
20:56:39:508 read my-ddf.json
...
20:56:41:107 DEV found DDF for 0x<redacted>, path: /usr/share/deCONZ/devices/vendor/my-ddf.json
```

**Comment by phdelodder** [comment]
The volume `/opt/deCONZ ` is exposed and you can mount it like: `-v /opt/deconz:/opt/deCONZ`, it is also use as the app data directory. 
@Mimiix perhaps you can assist with the location of custom DDF files?

**Comment by blue5h1ft** [comment]
I have a similar question – it seems to work (kind of) by placing the file in the exposed `opt/deCONZ/devices` folder, however, I'm struggling with the `general.xml` as described in this PR: https://github.com/dresden-elektronik/deconz-rest-plugin/pull/6547

**Comment by Mimiix** [comment]
I can not. Best to ask in the Deconz discord dev chat @phdelodder

**Comment by aradmidias** [comment]
@blue5h1ft is right: I monitored the File-System Access with _inotify_ and can confirm, that placing the DDF files underneath `/opt/deCONZ/devices/` **within the Container** will cause deCONZ to pick them up. An additional `vendor/` folder is not required, but may come in handy, lateron.
