### ISSUE TITLE
Where to place button_maps.json?

### ISSUE THREAD

**Issue by Sjonnie2018** [deconz-community/deconz-docker#174]
Hi All,

I have a MOES 3 gang switch (model: TS0043) for which I have to edit/create a button_maps.json. But I can't find the location of this file; neither in the container or the persistent volume I created (refers to /opt/deconz).

Anyone have an idea where to place the file?

More info here: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6724

TIA

**Comment by senilio** [comment]
There should be a `devices` folder on the persistent storage volume... `/opt/deCONZ/devices`

**Comment by Sjonnie2018** [comment]
I am sorry for my late reply!

Thank you for your support. I am currently rebuilding my Docker server and will investigate my issue when the rebuild is done.

Will try and test your suggestion on the new build and report back.

**Comment by Sjonnie2018** [comment]
Rebuilt my server and placed the button_maps.json and the moes.ddf in the devices folder on the persistent volume. Unfortunately the button maps are not read/recognized after a restart of the deCONZ container.

I am open to ideas!

**Comment by WhistleMaster** [comment]
I suggest that you post on the Deconz git [here](https://github.com/dresden-elektronik/deconz-rest-plugin/issues) as it seems your problem is not related to the Docker itself, otherwise the Deconz Discord [here](https://discord.gg/3XGEYY9).

**Comment by Sjonnie2018** [comment]
Where they explicitly suggested to ask the question overhere.

Hmmm classic case of "from pillar to post"

Tx!
