### ISSUE TITLE
Conbee II not displayed in GUI

### ISSUE THREAD

**Issue by Throbin999** [deconz-community/deconz-docker#177]
Hi,

I've migrated my old Deconz docker (running on QNAP nas) to this new community build. When using a different version than 2.14.00 there's no info for my Conbee II stick on the gateway page. I've tried v2.17.00, stable and latest release. All version work in terms of functionality meaning stick is detected and lights/sensors can be managed.

![deconze2 14](https://user-images.githubusercontent.com/125730776/219852055-50d82910-f4c1-44f5-a473-dfd601ed115f.JPG)
![deconz2 17](https://user-images.githubusercontent.com/125730776/219852061-e49aab40-15ba-496f-97e0-89b0cd4cfc54.JPG)

**Comment by senilio** [comment]
Unrelated to Docker, but this sounds like a browser cache issue. Try another browser and or private window etc.

**Comment by Throbin999** [comment]
Thanks for the swift reply. Damn, after numerous tries with different versions and page refresh/logout I never thought about that.
I've loaded the stable version and indeed, a inPrivate browser window displays all info correctly.
Thank you!
