### ISSUE TITLE
Raspbee 2 is not recognised on NanoPi Neo

### ISSUE THREAD

**Issue by marvin-nerlich** [deconz-community/deconz-docker#178]
I looked anywhere for an answer to my problem but I wasn'T able to find a solution.

I had troubles with setting up the container due to the nonexistence of ```/dev/ttyAMA0```.
I finally set up the container with the ```/dev/ttyS0``` variable.
Am I doing anything wrong becaue the container seems to work fine. There is just no recognisation of the Raspbee II hat..

**Comment by senilio** [comment]
Is the Raspbee recognized by the server? If that's not the case, this is the wrong place to ask :)

I guess you can check by using the flasher tool, and flash the latest firmware of the Raspbee.
