### ISSUE TITLE
docker deconz not starting on amd64 with VNC enabled

### ISSUE THREAD

**Issue by helbgd** [deconz-community/deconz-docker#184]
I tried a lot recently to get VNC working again but I am not able to

while having verbose startup active I got following doing docker logs deconz

```
==============================================================================

tigervncserver: /usr/bin/Xtigervnc did not start up, please look into '/home/deconz/.vnc/deconz:5900.log' to determine the reason! -1
+ export DISPLAY=:0
+ [ 0 = 0 ]
+ echo [deconzcommunity/deconz] noVNC Disabled
[deconzcommunity/deconz] noVNC Disabled
+ [ /dev/ttyACM0 != 0 ]
+ DECONZ_OPTS=--auto-connect=1         --appdata=/opt/deCONZ         --dbg-info=1         --dbg-aps=0         --dbg-zcl=0         --dbg-ddf=0         --dbg-dev=0         --dbg-zdp=0         --dbg-ota=0         --dbg-error=0         --dbg-http=0         --http-port=80         --ws-port=443 --dev=/dev/ttyACM0
+ [ 0 != 1 ]
+ DECONZ_OPTS=--auto-connect=1         --appdata=/opt/deCONZ         --dbg-info=1         --dbg-aps=0         --dbg-zcl=0         --dbg-ddf=0         --dbg-dev=0         --dbg-zdp=0         --dbg-ota=0         --dbg-error=0         --dbg-http=0         --http-port=80         --ws-port=443 --dev=/dev/ttyACM0 --upnp=0
+ mkdir -p /opt/deCONZ/otau
+ ln -sfT /opt/deCONZ/otau /home/deconz/otau
+ chown deconz:deconz /home/deconz/otau
+ chown deconz:deconz /opt/deCONZ -R
+ exec gosu deconz /usr/bin/deCONZ --auto-connect=1 --appdata=/opt/deCONZ --dbg-info=1 --dbg-aps=0 --dbg-zcl=0 --dbg-ddf=0 --dbg-dev=0 --dbg-zdp=0 --dbg-ota=0 --dbg-error=0 --dbg-http=0 --http-port=80 --ws-port=443 --dev=/dev/ttyACM0 --upnp=0
qt.qpa.xcb: could not connect to display :0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

+ echo [deconzcommunity/deconz] Starting deCONZ...
[deconzcommunity/deconz] Starting deCONZ...
+ echo [deconzcommunity/deconz] Current deCONZ version: 2.21.01
[deconzcommunity/deconz] Current deCONZ version: 2.21.01
+ echo [deconzcommunity/deconz] Web UI port: 80
```

I installed procps into the docker container and did a ps:

```
root@deconz:/# ps auxwww
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0   2484   652 pts/0    Ss+  21:53   0:00 /bin/sh /start.sh
root         7  0.0  0.0   4164  2176 pts/1    Ss   21:53   0:00 /bin/bash
deconz      47  0.2  0.0  15244 10812 pts/0    S+   21:53   0:00 /usr/bin/perl /usr/bin/tigervncserver -SecurityTypes VncAuth,TLSVnc :0
deconz      58  0.0  0.0  15244  9564 pts/0    S+   21:53   0:00 /usr/bin/perl /usr/bin/tigervncserver -SecurityTypes VncAuth,TLSVnc :0
deconz      59  0.7  0.0 2826124 40108 ?       Ssl  21:53   0:00 /usr/bin/Xtigervnc :0 -rfbport 5900 -localhost=0 -SecurityTypes VncAuth,TLSVnc -PasswordFile /home/deconz/.vnc/passwd -ClientWaitTimeMillis 30000 -geometry 1920x1200 -desktop deconz:0 (deconz) -depth 24 -auth /home/deconz/.Xauthority
root       423  0.0  0.0   6760  2036 pts/1    R+   21:54   0:00 ps auxwww
root@deconz:/# root@openmediavault:/HelmuthSSD/Docker/deconz/config/vnc# 
```
/usr/bin/Xtigervnc :0 -rfbport 5900 -localhost=0 -SecurityTypes VncAuth,TLSVnc -PasswordFile /home/deconz/.vnc/passwd -ClientWaitTimeMillis 30000 -geometry 1920x1200 -desktop deconz:0 (deconz) -depth 24 -auth /home/deconz/.Xauthority

I am a bit confused about -desktop deconz:0 (deconz) is this as expected ?
how can I add -verbose into startup of Xtigervnc to get more debug output ?

For the error message:
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
That means the builtin QT Application in the phoscon app is not beeing able to start ... How can I debug that ?

**Comment by phdelodder** [comment]
Can you share the complete docker log with `DECONZ_START_VERBOSE=1` and the docker run or compose?

**Comment by helipus** [comment]
Is there any solution for this problem because I actually have the same and don't find a working solution yet.

**Comment by phdelodder** [comment]
I can't reproduce it my self and with the available info it's hard to determine what is going wrong.

**Comment by helipus** [comment]
I found a solution now and did the following things:
1. The hostname was named after the docker container when I created it but it did had to be namend like the hostname on my Synology NAS. I did check it with writing "hostname" an the bash terminal on my Synology. The I recreated the docker container with this exact name. 
2. I changed the DECONZ_VNC_PORT to 5902
This did the trick for me.

Month before I also had trouble with the Conbee Stick.
This was solved by this line:
DECONZ_DEVICE: /dev/ttyACM0

Everything is working now and I can login to VNC via the VNC Viewer App on windows

**Comment by nilleiz** [comment]
Why is this closed? 
This is not a fix.
I have got the exact same problem on my ubuntu docker host.
[helipus](https://github.com/helipus)
I do not understand where this hostname thing must be set?
Can you give me a heads up?

**Comment by helipus** [comment]
> Why is this closed?
Yeah your are right. It should not be closed because I just found a work around.



> I do not understand where this hostname thing must be set?
> Can you give me a heads up?
I did set up a new docker container and gave this the name of my hostname. I did check it with writing "hostname" an the bash terminal on my Synology. The I recreated the docker container with this exact name.
It looks like this now:
![image](https://github.com/deconz-community/deconz-docker/assets/19687604/e11613e9-e2e2-4cc9-83fc-a79b56bcf141)

If I name the docker container anything else it did not work.

**Comment by nilleiz** [comment]
> > Why is this closed?
> > Yeah your are right. It should not be closed because I just found a work around.
> 
> > I do not understand where this hostname thing must be set?
> > Can you give me a heads up?
> > I did set up a new docker container and gave this the name of my hostname. I did check it with writing "hostname" an the bash terminal on my Synology. The I recreated the docker container with this exact name.
> > It looks like this now:
> > ![image](https://github.com/deconz-community/deconz-docker/assets/19687604/e11613e9-e2e2-4cc9-83fc-a79b56bcf141)
> 
> If I name the docker container anything else it did not work.

You say, that you just name your container after the dns name of your synology an then it works for you?

**Comment by helipus** [comment]
> You say, that you just name your container after the dns name of your synology an then it works for you?
yes. But a rename doesn't work. I need to create a new docker container with this name.

**Comment by nilleiz** [comment]
This is not working.
Deleted the container in portainer, recreated from stack, with naming the container, hostname and servicename after the server it is running on.

`2023-10-17T08:43:21.706528147Z [deconzcommunity/deconz] Starting deCONZ...
2023-10-17T08:43:21.706608182Z [deconzcommunity/deconz] Current deCONZ version: 2.19.01
2023-10-17T08:43:21.706619400Z [deconzcommunity/deconz] Web UI port: 8090
2023-10-17T08:43:21.706636848Z [deconzcommunity/deconz] Websockets port: 8091
2023-10-17T08:43:21.706646870Z [deconzcommunity/deconz] Using options --auto-connect=1 --appdata=/opt/deCONZ --dbg-info=1 --dbg-aps=0 --dbg-zcl=0 --dbg-ddf=0 --dbg-dev=0 --dbg-zdp=0 --dbg-ota=0 --dbg-error=0 --dbg-http=0 --http-port=8090 --ws-port=8091
2023-10-17T08:43:21.706657458Z [deconzcommunity/deconz] Modifying user and group ID
2023-10-17T08:43:21.706667216Z [deconzcommunity/deconz] Checking device group ID
2023-10-17T08:43:21.711881507Z [deconzcommunity/deconz] VNC port: 5900
2023-10-17T08:43:21.717475102Z [deconzcommunity/deconz] VNC DISABLE PASSWORD: 0
2023-10-17T08:43:21.807702424Z hostname: Name or service not known
2023-10-17T08:43:21.938884182Z tigervncserver: Could not acquire fully qualified host name of this machine.
2023-10-17T08:43:22.044313236Z hostname: Name or service not known
2023-10-17T08:43:22.174906360Z tigervncserver: Could not acquire fully qualified host name of this machine.
2023-10-17T08:43:22.266268330Z hostname: Name or service not known
2023-10-17T08:43:22.395335913Z tigervncserver: Could not acquire fully qualified host name of this machine.
2023-10-17T08:43:22.763070930Z WebSocket server settings:
2023-10-17T08:43:22.763133391Z   - Listen on :6080
2023-10-17T08:43:22.763152991Z   - Web server. Web root: /usr/share/novnc
2023-10-17T08:43:22.763566151Z   - SSL/TLS support
2023-10-17T08:43:22.763623675Z   - Backgrounding (daemon)`

Could a dev please take a look at this? 
I can't really use the purchased product at this stage...

**Comment by nilleiz** [comment]
"Fixed" it
Was running the container in host network.
Changing to a bridge network, mapping the ports and not setting a hostname in portainer made the services come up again when VNC is enabled.
So this has nothing to do with the containername, as I expected.
At least not on a ubuntu 22.04, with portainer.

**Comment by senilio** [comment]
Good stuff. tigervncserver is really picky when the container reports no hostname. I'll see if we can trick it into seeing a hostname even if none is set.

**Comment by senilio** [comment]
May I ask for some assistance in troubleshooting the issue? Could you start up the container in a state where you know the VNC server will fail, then open a shell to the container and pull some data? I'm interested in what the `hostname` command will return, as well as what environment variables are set.

To get a shell in the running container you can run `docker exec -it deconz sh`.

Then run and report back the result of `hostname`, `env`, `cat /etc/hostname`, `cat /etc/hosts`.

**Comment by senilio** [comment]
I tested a workaround in the startup script for situations where the hostname is not properly set within the container.

Please try the `dev` tag, feedback is welcome. 

https://hub.docker.com/layers/deconzcommunity/deconz/dev/images/sha256-b2b3af10844c893bbf103153f3791c01b443d91321b25522143314bab84c967b?context=explore

**Comment by helipus** [comment]
Hi senilio,
I would like to help.

> Could you start up the container in a state where you know the VNC server will fail, then open a shell to the container and pull some data? I'm interested in what the `hostname` command will return, as well as what environment variables are set.
I did start the container with version 2.23.0. It failed and stopped after a few second so I can't start a terminal to try what you did ask for:
The log shows:
![image](https://github.com/deconz-community/deconz-docker/assets/19687604/10f88e57-aba1-4800-af80-f78ba8e2b90c)

It then did try this:
> Please try the `dev` tag, feedback is welcome.
It fails again with the same errors.
The log shows:
![image](https://github.com/deconz-community/deconz-docker/assets/19687604/73c1cbf6-7968-44dc-901d-5e5818f6b402)

**Comment by senilio** [comment]
Thanks!

Synology seems to be doing something funky when running containers in host networking mode. Other examples:

https://www.synology-forum.de/threads/pi-hole-fehlermeldung.111688/
https://discourse.pi-hole.net/t/pihole-on-synology-docker-nas-giving-issues/54328/3
https://www.reddit.com/r/homebridge/comments/10xq0lz/hostname_name_or_service_not_known/

My workaround in clearly did not work.

I am rebuilding the container to include the debug commands I need. It's ready to test in about 20 minutes.

**Comment by helipus** [comment]
> I am rebuilding the container to include the debug commands I need. It's ready to test by pulling the dev tag again

hmm. I just don't see any debug command outputs:
![image](https://github.com/deconz-community/deconz-docker/assets/19687604/e13fd117-621d-4837-8dfa-f96027d12494)

**Comment by senilio** [comment]
Sorry, the last build failed. I've redone it now and confirmed the [new image](https://hub.docker.com/layers/deconzcommunity/deconz/dev/images/sha256-b2b3af10844c893bbf103153f3791c01b443d91321b25522143314bab84c967b?context=explore) is updated

**Comment by helipus** [comment]
Okay the new version startet! Here is the log: This time with debug:
![image](https://github.com/deconz-community/deconz-docker/assets/19687604/99db6a21-e586-401e-a276-9e417e9a2d13)
![image](https://github.com/deconz-community/deconz-docker/assets/19687604/e4fb8065-b22c-47b0-a7e9-2f1150d1897d)
![image](https://github.com/deconz-community/deconz-docker/assets/19687604/c1c35412-581b-48c1-9b9e-7369b529e206)
I think this is enough from the log, right?

**Comment by senilio** [comment]
Thanks a lot for that! Seems it worked this time. I've cleaned up the code and built yet another dev image. If you could try it out one last time and verify it still works, I think we're ready to roll out the fix for the other tags as well.

**Comment by helipus** [comment]
Sadly I have to report that it failed again:
![image](https://github.com/deconz-community/deconz-docker/assets/19687604/ef8c2ca3-659e-4a09-8f30-1951deb94659)
Sorry.

**Comment by senilio** [comment]
Phew, I'm rebuilding, please retry.

**Comment by helipus** [comment]
Looks like we are running again. :-) Thanks for your work!
![image](https://github.com/deconz-community/deconz-docker/assets/19687604/73cf68f7-f4f2-4678-9146-a6ccc836bee4)
![image](https://github.com/deconz-community/deconz-docker/assets/19687604/c03ef71c-d8cf-4d2f-bf1d-3f830e2a4b49)
![image](https://github.com/deconz-community/deconz-docker/assets/19687604/ec7a2922-752e-4775-b8b8-8feb4d9a7ef1)

**Comment by senilio** [comment]
No worries, thanks a lot for helping out with testing! The fix will be out in the next release.
