### ISSUE TITLE
Nginx and deconz working correctly

### ISSUE THREAD

**Issue by nlincke** [deconz-community/deconz-docker#185]
Hi,

i have deconz running and would like to put it behind a proxy....
Its kind of working but i cannot login.

and it is because its sending the login to the docker ip and not the fqdn i set up for it.

This is the consol output of the nginx webpage:
![image](https://user-images.githubusercontent.com/31100286/227747478-a0e448e5-4953-4556-b012-b2171d80c7f5.png)

172.19.0.2 cant be reached because is within the docker network only....
Any idea what i do wrong?

Thanks already....

**Comment by nlincke** [comment]
I think its related to : https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1279

**Comment by senilio** [comment]
Inability to run behind proxy is not related to this image. Try the forum.
