### ISSUE TITLE
Provide changelog

### ISSUE THREAD

**Issue by nliaudat** [deconz-community/deconz-docker#187]
The version.json changes frequently, but there is fast no commit ahead or only small typo fix.

Please provide a changelog and do not change version if no changes are made in the main code. 

Regards

**Comment by phdelodder** [comment]
When the version.json changes it's because there is a new release of deconz beta or stable.

**Comment by QuantumLibet** [comment]
> When the version.json changes it's because there is a new release of deconz beta or stable.

That is certainly true, but a change in version.json does not explain what has changed. Some release notes or change log or whatever you would like to call it would be very helpful. Please think about this. Thank you.

**Comment by senilio** [comment]
Release notes can be found in upstream - https://github.com/dresden-elektronik/deconz-rest-plugin/releases
