### ISSUE TITLE
Deconz image uses a lot of energy/performance?

### ISSUE THREAD

**Issue by antgustech** [deconz-community/deconz-docker#191]
I recently added powertop to my machine. It seems that deconz image is using a lot of energy. Is there a way to perhaps make it more efficient?
![energy](https://user-images.githubusercontent.com/8721113/236215819-e31bc6d6-3fd6-48c1-8b4b-604b18d78125.PNG)

**Comment by phdelodder** [comment]
Check with deconz it self I would say

**Comment by senilio** [comment]
Unrelated to docker, closing
