### ISSUE TITLE
Empty content under Gateway

### ISSUE THREAD

**Issue by maximuss** [deconz-community/deconz-docker#195]
I just updated to the latest version of image.
I drove one that was 2 years and 3 months old, so thought it was time :)
It has also been fairly painless, but when I am logged in and go under the gateway to load my backup, there is a completely blank page! Only a picture of a ConBee key is shown and nothing more.
What surprises me a bit is that when I log in it says that the ip is 192.168.1.2 (which is my Ubuntu server), but when I am logged in it says that it is 172.17.0.17 which is the internal ip as docker assigns.
What did I do wrong?

![image](https://github.com/deconz-community/deconz-docker/assets/153221/cbbbfe29-7944-4571-b914-2b4f498e3a9d)

**Comment by phdelodder** [comment]
Don't think this related to docker, best to check the https://forum.phoscon.de/

**Comment by maximuss** [comment]
You are right - that's not docker. I realised that after i have posted.
Sorry about that

Den man. 19. jun. 2023 kl. 07.51 skrev Philippe Delodder <
***@***.***>:
