### ISSUE TITLE
Cant acess my Phoscon App

### ISSUE THREAD

**Issue by basti0023** [deconz-community/deconz-docker#198]
Hi, I'm trying to set up deCONZ via Docker on a Raspberry Pi 4B. I'm using a RaspBee 2 for deCONZ. I'm pretty sure deCONZ is up and running, but I can't find my Phoscon gateway in my network. I've tried accessing it through its IP address and port, as well as the Phoscon link, but no luck.

Here's the Docker Compose file I'm using:
version: "3"
services:
  deconz:
    image: deconzcommunity/deconz:stable
    container_name: deconz
    restart: always
    privileged: true
    ports:
      - 800:800
      - 443:443
    volumes:
      - /opt/deCONZ:/opt/deCONZ
    devices:
      - /dev/ttyS0
    environment:
      - TZ=Europe/Berlin
      - DECONZ_WEB_PORT=8080
      - DECONZ_WS_PORT=443
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTA=0
      - DEBUG_HTTP=0
      - DECONZ_DEVICE=/dev/ttyS0
      - DECONZ_START_VERBOSE=0

And thats my Docker Log:
[deconzcommunity/deconz] Starting deCONZ...
[deconzcommunity/deconz] Current deCONZ version: 2.22.02
[deconzcommunity/deconz] Web UI port: 8080
[deconzcommunity/deconz] Websockets port: 443
[deconzcommunity/deconz] Using options --auto-connect=1 --appdata=/opt/deCONZ --dbg-info=1 --dbg-aps=0 --dbg-zcl=0 --dbg-ddf=0 --dbg-dev=0 --dbg-zdp=0 --dbg-ota=0 --dbg-error=0 --dbg-http=                       0 --http-port=8080 --ws-port=443
[deconzcommunity/deconz] Modifying user and group ID
[deconzcommunity/deconz] Checking device group ID
[deconzcommunity/deconz] VNC Disabled
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-deconz'
libpng warning: iCCP: known incorrect sRGB profile
This plugin does not support propagateSizeHints()
This plugin does not support propagateSizeHints()
This plugin does not support propagateSizeHints()
11:17:09:367 HTTP Server listen on address 0.0.0.0, port: 8080, root: /usr/share/deCONZ/webapp/
11:17:09:385 /opt/deCONZ/config.ini exists and is writeable
11:17:09:385 /opt/deCONZ/zll.db exists and is writeable
11:17:09:491 dev /dev/ttyAMA0
11:17:09:491 dev /dev/ttyS0
11:17:09:491 COM: /dev/ttyS0 / serialno: , RaspBee
11:17:09:491 ZCLDB init file /opt/deCONZ/zcldb.txt
11:17:09:609 DDF enabled for Gold status
11:17:09:005 gw run mode: normal
11:17:09:005 GW sd-card image version file does not exist: /opt/deCONZ/gw-version
11:17:10:005 sd-card cid: 035344534433324785ffffffff016300
11:17:10:006 DB sqlite version 3.34.1
11:17:10:007 DB PRAGMA page_count: 46
11:17:10:007 DB PRAGMA page_size: 4096
11:17:10:007 DB PRAGMA freelist_count: 0
11:17:10:007 DB file size 188416 bytes, free pages 0
11:17:10:007 DB PRAGMA user_version: 9
11:17:10:007 DB cleanup
11:17:10:008 DB create temporary views
11:17:10:027 [INFO] - Timezone read is 'Etc/UTC'
11:17:10:027 [INFO] - Environment variable TZ found: Europe/Berlin...
11:17:10:028 Started websocket server on 0.0.0.0, port: 443
11:17:10:031 [INFO] - Found file containing button maps. Parsing data...
11:17:10:046 [INFO] - Button maps loaded.
11:17:10:047 found node plugin: libde_rest_plugin.so - REST API Plugin
11:17:10:048 found node plugin: libde_signal_plugin.so - Signal Monitor Plugin
11:17:10:059 found node plugin: libstd_otau_plugin.so - STD OTAU Plugin
11:17:10:090 dlg action: Read binding table
11:17:11:098 dev /dev/ttyAMA0
11:17:11:098 dev /dev/ttyS0
11:17:11:098 COM: /dev/ttyS0 / serialno: , RaspBee
11:17:12:679 Device firmware version 0x26690700 RaspBee
11:17:12:705 unlocked max nodes: 512
11:17:12:705 Device protocol version: 0x010E
11:17:12:743 new node - ext: 0x00212effff0645aa, nwk: 0x0000
11:17:12:941 Current channel 25
11:17:13:005 CTRL got nwk update id 3
11:17:13:025 CTRL ANT_CTRL 0x03
11:17:13:213 APS-DATA.indication from unknown node 0x8072
11:17:13:289 unknown node 0x00158D000344B098 (0x8072), lqi: 199
11:17:13:289 APS-DATA.indication from unknown node 0x00158D000344B098
11:17:13:321 unknown node 0x00158D0003E5B3BA (0xFD56), lqi: 199
11:17:13:321 APS-DATA.indication from unknown node 0x00158D0003E5B3BA
11:17:14:635 DB UPDATE device_descriptors SET data = x'10400f3511472b0040002b0000', timestamp = 1689412634 WHERE device_id = (SELECT id FROM devices WHERE mac = '00:21:2e:ff:ff:06:45:aa')                        AND endpoint = 0 AND type = 2
11:17:14:635 DB INSERT INTO device_descriptors (device_id, endpoint, type, data, timestamp) SELECT id, 0, 2, x'10400f3511472b0040002b0000', 1689412634 FROM devices WHERE mac = '00:21:2e:ff                       :ff:06:45:aa'
11:17:15:131 DB UPDATE device_descriptors SET data = x'01040105000105000006000a0019000105040100200000050205', timestamp = 1689412635 WHERE device_id = (SELECT id FROM devices WHERE mac = '                       00:21:2e:ff:ff:06:45:aa') AND endpoint = 1 AND type = 4
11:17:15:131 DB INSERT INTO device_descriptors (device_id, endpoint, type, data, timestamp) SELECT id, 1, 4, x'01040105000105000006000a0019000105040100200000050205', 1689412635 FROM device                       s WHERE mac = '00:21:2e:ff:ff:06:45:aa'
11:17:15:147 GW update firmware found: /usr/share/deCONZ/firmware/deCONZ_ConBeeII_0x26720700.bin.GCF
11:17:15:336 Announced to internet https://phoscon.de/discover
11:17:15:336 discovery server date: Sat, 15 Jul 2023 09:17:15 GMT
11:17:15:336     local time seems to be ok
11:17:15:610 DB UPDATE device_descriptors SET data = x'f2e0a164000100012100', timestamp = 1689412635 WHERE device_id = (SELECT id FROM devices WHERE mac = '00:21:2e:ff:ff:06:45:aa') AND en                       dpoint = 242 AND type = 4
11:17:15:610 DB INSERT INTO device_descriptors (device_id, endpoint, type, data, timestamp) SELECT id, 242, 4, x'f2e0a164000100012100', 1689412635 FROM devices WHERE mac = '00:21:2e:ff:ff:                       06:45:aa'
11:17:15:730 unknown node 0x00158D0003E5B3BA (0xFD56), lqi: 199
11:17:15:730 APS-DATA.indication from unknown node 0x00158D0003E5B3BA
11:17:17:185 unknown node 0x00158D0005080FEB (0xBA29), lqi: 215
11:17:17:185 APS-DATA.indication from unknown node 0x00158D0005080FEB
11:17:18:102 DEV Tick.Init: booted after 8000 seconds

**Comment by senilio** [comment]
Try exposing port 8080 instead of 800

**Comment by basti0023** [comment]
that worked thanks a lot!
