### ISSUE TITLE
Deconz Web Page behind Rproxy as a subfolder

### ISSUE THREAD

**Issue by ich92** [deconz-community/deconz-docker#199]
Hello,

i wanted to reach the deconz web page on a address https://hostname/deconz/.
Therefore I wanted to use an nginx rproxy docker
It does work but there are a lot of problems:
I tried it with:
` location /deconz/ {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_pass http://172.26.0.2:80/;
    }`

I can connect to https://hostname/deconz/ but I get forwareded to https://hostname/pwa/. After handling this I get another call to https://hostname/api/ when I try to login.
Is it possible to say deconz to forward to relative path not to absolute?
for the web app: ./pwa/ insted of hostname/pwa/
for the api: ./api/ insted of hostname/api/
for the old webapp: ./owa/ insted of hostname/index.html

Hope anyone has a Idea how to solve the problem.

**Comment by phdelodder** [comment]
I can't help you with that, never used a proxy in front of deconz perhaps the forum could be of assistants
