### ISSUE TITLE
Latest tag points to beta release and not to the latest stable

### ISSUE THREAD

**Issue by tseroo** [deconz-community/deconz-docker#201]
The latest and the beta tags point to the same version. I guess that's not intended..
![image](https://github.com/deconz-community/deconz-docker/assets/10330889/b8a3580d-0b8b-4185-a251-f302d0edc0f5)

**Comment by senilio** [comment]
It's intended.

**Comment by senilio** [comment]
It's probably intended.

beta tag will point to the latest beta
latest tag till point to the latest version regardless of beta or stable

**Comment by tseroo** [comment]
Hmm, that's very confusing then, because in the [release notes](https://github.com/dresden-elektronik/deconz-rest-plugin/releases) it is different. There latest is the stable release
![image](https://github.com/deconz-community/deconz-docker/assets/10330889/63505c64-d32d-4c96-9f51-6045ee5323b6)

where as beta is marked as pre-release
![image](https://github.com/deconz-community/deconz-docker/assets/10330889/c888f812-e341-4018-9886-2762ba21d011)

**Comment by senilio** [comment]
We don't follow that naming.
