### ISSUE TITLE
user mode

### ISSUE THREAD

**Issue by acht** [deconz-community/deconz-docker#202]
Hi,

after starting the container:

docker run -it --name=deconz --user x:x --device=/dev/ttyACM0   -e DECONZ_START_VERBOSE=1 deconzcommunity/deconz:stable

(x is the local user id)

I get some errors and the execution stops:
...
+ mkdir -p /opt/deCONZ/otau
mkdir: cannot create directory '/opt/deCONZ/otau': Permission denied
+ ln -sfT /opt/deCONZ/otau /home/deconz/otau
ln: failed to create symbolic link '/home/deconz/otau': Permission denied
+ chown deconz:deconz /home/deconz/otau
chown: cannot access '/home/deconz/otau': No such file or directory
+ chown deconz:deconz /opt/deCONZ -R
chown: changing ownership of '/opt/deCONZ': Operation not permitted
+ exec gosu deconz /usr/bin/deCONZ --auto-connect=1 --appdata=/opt/deCONZ --dbg-info=1 --dbg-aps=0 --dbg-zcl=0 --dbg-ddf=0 --dbg-dev=0 --dbg-zdp=0 --dbg-ota=0 --dbg-error=0 --dbg-http=0 --http-port=80 --ws-port=443 -platform minimal
error: failed switching to "deconz": operation not permitted

(Having opt/deCONZ in a volume gives the same result.)

docker run -it  --entrypoint "/bin/bash" deconzcommunity/deconz:stable
mkdir -p /opt/deCONZ/otau
ln -sfT /opt/deCONZ/otau /home/deconz/otau

Any help is welcome

**Comment by senilio** [comment]
Try setting these to match whatever you set as `x:x`

DECONZ_UID
DECONZ_GID

**Comment by senilio** [comment]
Closing due to lack of feedback
