### ISSUE TITLE
Failure writing output while updating the firmware

### ISSUE THREAD

**Issue by mariomaz87** [deconz-community/deconz-docker#205]
Hi,
I'm trying to update the firmware of my Conbee II.  I launch the script, I select the device path and then enter the name of the firmware file. I type "y" to download it and I get:

Firmware file: deCONZ_ConBeeII_0x26780700.bin.GCF 
 
File not found locally. Enter Y to download from http://deconz.dresden-elektronik.de/deconz-firmware/deCONZ_ConBeeII_0x26780700.bin.GCF: y
 
Downloading...
 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to create the file 
Warning: /usr/share/deCONZ/firmware/deCONZ_ConBeeII_0x26780700.bin.GCF: No 
Warning: such file or directory
  1  159k    1  2896    0     0  41371      0  0:00:03 --:--:--  0:00:03 41371
curl: (23) Failure writing output to destination

Download Error! Please re-run this script...

I tried running the script several times with the same results. I'm running the docker image on a Raspberry 4.
Do you have any idea? Thanks!

**Comment by mithomas** [comment]
Manually creating the `firmware` subdirectory in `/usr/share/deCONZ/` (within the _deconzcommunity/deconz_, obviously) fixed this.

**Comment by senilio** [comment]
This will be fixed in https://github.com/deconz-community/deconz-docker/pull/213
