### ISSUE TITLE
No Gateway when login in by domain instead of IP

### ISSUE THREAD

**Issue by furchtlos76** [deconz-community/deconz-docker#210]
If i login via 192.168.1.x  i am redirected to
http://192.168.1.x/pwa/login.html#

and below the brown p there is Phoscon-GW button shown on the same IP

if i login via nginx proxy manager by domain deconz.domain.de i am redirected to
deconz.domain.de/pwa/login.html#

BUT i only get the brown P but NO Button below to login the gateway.

Anyone any idea?

**Comment by senilio** [comment]
I understand the issue, but I don't think it's related to docker. Unfortunately the developers of Phoscon does not read GitHub issues, so I think the best way to get their attention is to open a new topic on the forum. 

https://forum.phoscon.de/
