### ISSUE TITLE
Failure updating firmware from docker image using the provided instructions

### ISSUE THREAD

**Issue by iago1460** [deconz-community/deconz-docker#214]
docker image: `deconzcommunity/deconz:2.24.1`

It seems the download fails when trying to write into the directory:
 
`curl: (23) Failure writing output to destination`

### Workaround:
I managed to make it work just mounting the directory, basically adding the following to the step [3. Invoke the firmware update script:](https://github.com/deconz-community/deconz-docker#3-invoke-the-firmware-update-script)
 `-v $(pwd)/deconz/firmware:/usr/share/deCONZ/firmware/`

**Comment by senilio** [comment]
Thanks for reporting. This issue is fixed in https://github.com/deconz-community/deconz-docker/pull/213, which will be included in the next release.
