### ISSUE TITLE
Cannot Update Firmware of Conbee 2

### ISSUE THREAD

**Issue by tobeehh** [deconz-community/deconz-docker#216]
Have been updating Conbee many times on my Synology running Docker, however, now the script fails:

`root@Syno2:~# docker run -it --rm --entrypoint "/firmware-update.sh" --privileged --cap-add=ALL -v /dev:/dev -v /lib/modules:/lib/modules -v /sys:/sys deconzcommunity/deconz
-------------------------------------------------------------------
 
             deconzcommunity/deconz Firmware Flashing Script
 
                       Version: 0.8
 
-------------------------------------------------------------------
 
 
Listing attached devices...
 
sh: 1: udevadm: not found
sh: 1: udevadm: not found
no devices found
Path              | Serial      | Type
------------------+-------------+---------------
 
Enter the full device path, or press Enter now to exit.
 
Device path .: 0
 
-------------------------------------------------------------------
 
Firmware available for flashing:
ls: cannot access '/usr/share/deCONZ/firmware/': No such file or directory
 
Enter the firmware file name from above, including extension.
Alternatively, you may enter the name of a firmware file to download
from any of the following sources:
 - http://deconz.dresden-elektronik.de/deconz-firmware/         (stable)
 - http://deconz.dresden-elektronik.de/deconz-firmware/beta/    (beta)
 
If you wish to exit, just hit Enter.
 
Firmware file: 

Exiting...
`

**Comment by senilio** [comment]
They decided to omit the firmware directory in the package. Next release will contain a fix for this.

https://github.com/deconz-community/deconz-docker/pull/212/files#diff-22f112a20e8634a778071a41b6165c4ed9328f7f9831e71b57086365dfa8c56c

Temp fix = edit the FW_PATH or create /usr/share/deCONZ/firmware/
