### ISSUE TITLE
Most of the buttons dont work

### ISSUE THREAD

**Issue by tebbbb** [deconz-community/deconz-docker#218]
I can login and i see the firmware, but i cant go to advanced or reset the gateway. I get a bunch of js errors in the console. I am using the docker image an a raspberry pi with ubuntu

![Screenshot from 2023-11-18 05-59-31](https://github.com/deconz-community/deconz-docker/assets/144042203/edf75230-5cc0-4af3-8f58-9972ec181c2a)

**Comment by senilio** [comment]
We have nothing to do with Phoscon. This project just runs deCONZ in Docker as-is. Try the forum or ask on Discord. Unqualified guess: change browser.
