### ISSUE TITLE
Devices directory

### ISSUE THREAD

**Issue by Didier3L** [deconz-community/deconz-docker#224]
Bonjour,

Here is my mirrored volume in docker-compose

```
volumes:
           - /volume1/docker/deconz-community:/opt/deCONZ
```

With Deconz here is the default file location

![image](https://github.com/deconz-community/deconz-docker/assets/23530136/8b8fda05-050f-47cc-8414-b69af7b49094)
![image](https://github.com/deconz-community/deconz-docker/assets/23530136/d5009d02-5ff2-4269-bfc8-59869c8f098b)

Why don't the files exist ?
![image](https://github.com/deconz-community/deconz-docker/assets/23530136/e86fda50-847b-4808-842e-94ba37cc0c85)

**Comment by senilio** [comment]
Not sure what your are asking.

Top screenshot shows /usr/share/deCONZ/devices/
Bottom screenshot shows /opt/deCONZ/devices/

DDF is read from both places.

**Comment by Didier3L** [comment]
the tutorial indicates
-v /opt/deconz:/opt/deCONZ \

What is the /usr/share/deCONZ/devices/ directory used for?

**Comment by senilio** [comment]
> the tutorial indicates
> -v /opt/deconz:/opt/deCONZ \
> 
> What is the /usr/share/deCONZ/devices/ directory used for?

For DDF files that ships with deCONZ.

User provided files should be recognized in both dirs. The difference is that files in /usr/share is not stored on persistent storage.
