### ISSUE TITLE
Problem with firmware update

### ISSUE THREAD

**Issue by vineet-goel** [deconz-community/deconz-docker#229]
Hello,

I have conbee-II stick and using it with HomeAssistant OS.
I am trying to update the stick to the latest compatible firmware version avialable, [deCONZ_ConBeeII_0x26780700.bin.GCF](http://deconz.dresden-elektronik.de/deconz-firmware/deCONZ_ConBeeII_0x26780700.bin.GCF) as per the instructions defined [here](https://github.com/deconz-community/deconz-docker#3-invoke-the-firmware-update-script)

The process starts fine but get stuck at `query bootloader id V1`

Here are the logs
```
Device path .: /dev/ttyUSB1
Firmware file: deCONZ_ConBeeII_0x26780700.bin.GCF
Timeout .....: 60

Are the above values correct?
Enter Y to proceed, any other entry to exit: Y

Flashing...

read file success: /tmp/deCONZ_ConBeeII_0x26780700.bin.GCF (163244 bytes)
flash firmware
command UART reset done
query bootloader id V1
query bootloader id V1
query bootloader failed
retry: 54 seconds left
read file success: /tmp/deCONZ_ConBeeII_0x26780700.bin.GCF (163244 bytes)
flash firmware
command UART reset done
query bootloader id V1
query bootloader id V1
query bootloader id V1
query bootloader id V1
query bootloader id V1
query bootloader id V1
query bootloader id V1
query bootloader id V1
```

I have tried several times and always have the same result. 

Any suggestions on how to resolve this issue?

**Comment by senilio** [comment]
Was deCONZ stopped before running the update script?
