### ISSUE TITLE
Conbee3 config , docker compose 

### ISSUE THREAD

**Issue by nsk** [deconz-community/deconz-docker#231]
Hello ,

 for the conbee3 use last version : deconzcommunity/deconz:beta , flash the last firmware ... , add : -DECONZ_BAUDRATE=115200 on compose , I created a pull request, but I don't know if an admin can validate it 

 services:
  deconz:
    image: deconzcommunity/deconz:beta
    container_name: deconz
    restart: always
    privileged: true # This is important! Without it, the deCONZ image won't be able to connect to Conbee II.
    ports:
      - 8888:8888
      - 443:443
    volumes:
      - /opt/deCONZ:/opt/deCONZ
    devices:
      - /dev/ttyUSB0 # This is the USB device that Conbee II is running on.
    environment:
      - TZ=Europe/Zurich
      - DECONZ_WEB_PORT=8888
      - DECONZ_WS_PORT=443
      - DEBUG_INFO=1
      - DEBUG_APS=1
      - DEBUG_ZCL=1
      - DEBUG_ZDP=1
      - DEBUG_OTA=0
      - DEBUG_HTTP=0
      - DECONZ_DEVICE=/dev/ttyUSB0 # This is the USB device that Conbee II is running on.
      - DECONZ_START_VERBOSE=0
      - DECONZ_BAUDRATE=115200

**Comment by phdelodder** [comment]
I don't see a pull request.

**Comment by nsk** [comment]
@phdelodder there is a message that indicates that you must be an admin to make a pull request when you post
