### ISSUE TITLE
Feature request: Make dev-test-managed parameter configurable via environment variable

### ISSUE THREAD

**Issue by torandreroland** [deconz-community/deconz-docker#237]
It would be very welcome if dev-test-managed would be configurable as an environment variable to be able to set the DDF mode to something else than basic at startup.

**Comment by torandreroland** [comment]
Added pull request #238.

**Comment by phdelodder** [comment]
Merged can you please test?

**Comment by torandreroland** [comment]
Works. Thanks for merging!
