### ISSUE TITLE
No devices detected by update script

### ISSUE THREAD

**Issue by filip-van-hoeckel** [deconz-community/deconz-docker#239]
When running the update script on an Rpi3/Raspbee there are no devices detected - even when including it.

`docker run -it --rm --entrypoint "/firmware-update.sh" --privileged --cap-add=ALL -v /dev:/dev -v /lib/modules:/lib/modules -v /sys:/sys deconzcommunity/deconz`

When force feeding it the device and hard pointing it to the online firmware it even claims it cannot find the firmware, neither local nor online. Where would I start troubleshooting this?

**Comment by phdelodder** [comment]
Can you share the output?

**Comment by phdelodder** [comment]
I have just tried to reproduce it on my environments and I do get a list of devices. So either the device isn't attached to docker or it's not recognized. For the "available firmware", it checks the /tmp folder if any is present.

**Comment by filip-van-hoeckel** [comment]
The device _is connected otherwise I couldn't use it when not trying to perform the update. Should deconz be off or on when executing the commands?

**Comment by phdelodder** [comment]
I suggest deconz to be off and only running the docker with firmware.

**Comment by filip-van-hoeckel** [comment]
Deconz was off in my demo.

**Comment by senilio** [comment]
I don't think any of us owns a Raspbee and therefore it's hard to to know why the script doesn't detect the device.

For now I think it would be best to try to build GCFFlasher4 on your docker host, and try to flash from there. If you can wait a bit, I will attempt to build the binaries for RPi

**Comment by senilio** [comment]
Download the flasher for your arch here: https://github.com/dresden-elektronik/gcfflasher/releases/tag/v4.3.0-beta
Stop deCONZ and try flashing on your docker host.

**Comment by filip-van-hoeckel** [comment]
I appreciate the effort, but what arch do I select for a Rpi?

**Comment by senilio** [comment]
arm64 for 64 bit raspberry pi OS
armhf for 32 bit raspberry pi OS

This flasher binary have built in support for Raspbee, which will hopefully solve your issue

**Comment by filip-van-hoeckel** [comment]
OK, thanks, will try. This would mean powering down HassIO, buying a new card, installing Raspbian, getting this binary on it, then flashing. Correct? (I do wonder why updating firmware thru the UI was cancelled, considering the amount of work and risk involved.)

**Comment by senilio** [comment]
Something like that. By using the Raspbee, a lot of flexibility is sacrificed. Both in terms of firmware upgrades and ability to mitigate interference.

**Comment by filip-van-hoeckel** [comment]
Well, updating used to be two clicks (backup, update). Now it's about a weekend's work. I'm not sure this feels like progress.

**Comment by filip-van-hoeckel** [comment]
Sold the Raspbee and uninstalled Phoscon. Bought a HA zigbee stick instead. HUGE difference. Will never look back.
