### ISSUE TITLE
Problem with connecting to Conbee II on Synology DSM 6(.2.4)

### ISSUE THREAD

**Issue by mcormick** [deconz-community/deconz-docker#24]
Coming from a working marthoc docker (2.13.01) container I have troubles getting `deconzcommunity/docker` 2.13.02 to work on my Synology with DSM 6.2.4.

I `docker image pull deconzcommunity/deconz:latest`, which it does.

Then I run the container with the following (DSM docker json) settings:
```
{
   "cap_add" : [],
   "cap_drop" : [],
   "cmd" : "bash /start.sh",
   "cpu_priority" : 90,
   "devices" : null,
   "enable_publish_all_ports" : false,
   "enable_restart_policy" : false,
   "enabled" : false,
   "env_variables" : [
      {
         "key" : "PATH",
         "value" : "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      },
      {
         "key" : "DEBIAN_FRONTEND",
         "value" : "noninteractive"
      },
      {
         "key" : "DECONZ_VERSION",
         "value" : "2.13.02"
      },
      {
         "key" : "DECONZ_WEB_PORT",
         "value" : "80"
      },
      {
         "key" : "DECONZ_WS_PORT",
         "value" : "443"
      },
      {
         "key" : "DEBUG_INFO",
         "value" : "2"
      },
      {
         "key" : "DEBUG_APS",
         "value" : "2"
      },
      {
         "key" : "DEBUG_ZCL",
         "value" : "0"
      },
      {
         "key" : "DEBUG_ZDP",
         "value" : "0"
      },
      {
         "key" : "DEBUG_OTAU",
         "value" : "0"
      },
      {
         "key" : "DEBUG_ERROR",
         "value" : "0"
      },
      {
         "key" : "DECONZ_DEVICE",
         "value" : "0"
      },
      {
         "key" : "DECONZ_VNC_MODE",
         "value" : "1"
      },
      {
         "key" : "DECONZ_VNC_DISPLAY",
         "value" : "0"
      },
      {
         "key" : "DECONZ_VNC_PASSWORD",
         "value" : "mypass"
      },
      {
         "key" : "DECONZ_VNC_PASSWORD_FILE",
         "value" : "0"
      },
      {
         "key" : "DECONZ_VNC_PORT",
         "value" : "5900"
      },
      {
         "key" : "DECONZ_NOVNC_PORT",
         "value" : "6080"
      },
      {
         "key" : "DECONZ_UPNP",
         "value" : "1"
      },
      {
         "key" : "DECONZ_UID",
         "value" : "1000"
      },
      {
         "key" : "DECONZ_GID",
         "value" : "1000"
      },
      {
         "key" : "DECONZ_START_VERBOSE",
         "value" : "1"
      },
      {
         "key" : "LC_ALL",
         "value" : "C.UTF-8"
      },
      {
         "key" : "UDEV",
         "value" : "off"
      },
      {
         "key" : "TINI_VERSION",
         "value" : "0.18.0"
      }
   ],
   "exporting" : false,
   "id" : "d89e0b480dd7519190b518b715f9fc2aa667cfc0ad85dd1deeacff9442f70cd8",
   "image" : "deconzcommunity/deconz:latest",
   "is_ddsm" : false,
   "is_package" : false,
   "links" : [],
   "memory_limit" : 4294967296,
   "name" : "deCONZ-community",
   "network" : [
      {
         "driver" : "bridge",
         "name" : "bridge"
      }
   ],
   "network_mode" : "bridge",
   "port_bindings" : [
      {
         "container_port" : 5900,
         "host_port" : 1339,
         "type" : "tcp"
      },
      {
         "container_port" : 80,
         "host_port" : 1337,
         "type" : "tcp"
      }
   ],
   "privileged" : true,
   "shortcut" : {
      "enable_shortcut" : true,
      "enable_status_page" : false,
      "enable_web_page" : true,
      "web_page_url" : "http://deconz.local:1337"
   },
   "use_host_network" : false,
   "volume_bindings" : [
      {
         "host_volume_file" : "/docker/deconz/otau",
         "mount_point" : "/root/otau",
         "type" : "rw"
      },
      {
         "host_volume_file" : "/docker/deconz/config",
         "mount_point" : "/opt/deCONZ",
         "type" : "rw"
      }
   ]
}
```
The container itself starts, and `start.sh` shows the modifications made in https://github.com/deconz-community/deconz-docker/pull/20 
I do, however, get `failed open com status: (-3), path: /dev/ttyACM0` in the logs: [deCONZ-community.csv.log](https://github.com/deconz-community/deconz-docker/files/7546336/deCONZ-community.csv.log) (note; log is reversed)

```
ash-4.3# sudo docker exec -it deCONZ-community id 1000
uid=1000(deconz) gid=1000(deconz) groups=1000(deconz),0(root)
ash-4.3# sudo docker exec -it deCONZ-community ls -al /dev/ttyACM0
crw------- 1 root root 166, 0 Nov 16 12:43 /dev/ttyACM0
```

When I manually `sudo chmod g+rw /dev/ttyACM0` in a container console deCONZ starts and I can control devices via Zigbee:
```
ash-4.3# sudo docker exec -it deCONZ-community ls -al /dev/ttyACM0
crw-rw---- 1 root root 166, 0 Nov 16 12:24 /dev/ttyACM0
```
But now the Phoscon app does not load and the API (which Home Assistant talks to) does not seem to be running (Connection reset).

Any pointers would be appreciated.

**Comment by rnsc** [comment]
This is probably due to the fact that the new image doesn't run as root by default, so it cannot bind on port 80.
You should either force another UID/GID, or use a different port for the WS (ie: 8000).

**Comment by senilio** [comment]
Are you able to get the logs from the container while it's starting up?

**Comment by mcormick** [comment]
> Are you able to get the logs from the container while it's starting up?

Yes, well, the synology export of the logs; its a csv in reverse. I enabled DEBUG_INFO=2, DEBUG_APS=2 and DECONZ_START_VERBOSE=1:  [deCONZ-community.csv.log](https://github.com/deconz-community/deconz-docker/files/7546336/deCONZ-community.csv.log)

**Comment by phdelodder** [comment]
In the log I see the device /dev/ttyS0 in your comments I see device /dev/ttyACM0, could please specify the correct device eg: DECONZ_DEVICE=/dev/ttyUSB1

**Comment by mcormick** [comment]
> In the log I see the device /dev/ttyS0 in your comments I see device /dev/ttyACM0, could please specify the correct device eg: DECONZ_DEVICE=/dev/ttyACM0

Amazing. That works. I was thrown off by the mentioning of a "drop-in replacement" to the Marthoc container in the readme yesterday, not realizing that the two containers (marthoc and this one) are (somewhat) different from each other and might need additional configuration.

> This is due to the fact that the new image doesn't run as root by default, so it cannot bind on port 80.
> You should either force another UID/GID, or use a different port for the WS (ie: 8000).

This also helped in getting Phoscon back. Had to change the `DECONZ_WEB_PORT` in `Environment` tab (Synology DSM Docker). Don't forget to also change the port mapping in the `Port settings` tab. As a result I had to change port of the deCONZ integration for Home Assistant (`config/.storage/core.config_entries`) to bring everything back. Thank you all for your assistance.

**Comment by marithpl** [comment]
@mcormick Are you able to make an manual for migration from marthoc docker?
How did you run a docker with json setting?
