### ISSUE TITLE
Could not connect to Conbee 3

### ISSUE THREAD

**Issue by saxn-paule** [deconz-community/deconz-docker#241]
I recently bought a brand new Conbee III and have a fresh installation with Debian 12 on intel NUC 6.

The Conbee was updated on Windows PC with newest Firmware. Deconz installed via Docker Image.

With all deconz docker images (beta/stable/latest) I got the same issue.

failed to reconnect to network
COM: /dev/ttyUSB0 / serialno: , ConBee

ttyUSB0 is the right port as given by:
ls -al /dev/serial/by-id/usb-dresden_elektronik_ConBee_III_DE...........-port0
--> ../../ttyUSB0

The Deconz GUI is available and shows me the correct frontend version, depending on the image.

On the gateway page the firmware is "not connected"
zigbee channel 0 and network id "unknown" 

I also tried ttyACM0 and any other possibiliies I found in the web with no success.

Starting with sudo doesn't help. "privileged" parameter is set in the docker-compose.yaml.

My productive installation with ConBee I on Debian 9 runs without any issues on another NUC.

Any hints?

**Comment by senilio** [comment]
https://github.com/deconz-community/deconz-docker?tab=readme-ov-file#notes-for-conbee-3-users

**Comment by saxn-paule** [comment]
I added my user to the dialers group and set the baudrate. Restarted the system bot had no success.

``ỳaml
version: '3'

services:
  
  deconz:
    image: deconzcommunity/deconz:2.23.02
    container_name: deconz
    network_mode: host
    restart: always
    privileged: true
    volumes:
      - /home/psc/Docker-Env/deconz/data/:/opt/deCONZ
    devices:
      - /dev/ttyUSB0
    environment:
      - DECONZ_WEB_PORT=8080
      - DECONZ_WS_PORT=8443
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0
      - DECONZ_BAUDRATE=115200
      - DECONZ_UID=0
      - DECONZ_GID=0
      - DECONZ_VNC_MODE=0
      - DECONZ_DEVICE=/dev/ttyUSB0
      - DECONZ_VNC_PORT=5959
      - DECONZ_VNC_PASSWORD=xxxxxxxxx
 ``

**Comment by senilio** [comment]
I don't think Conbee 3 was yet supported in the version you try to run

**Comment by saxn-paule** [comment]
Yes you're right. With the "latest" release (2.25.2) it works now. Thank you very much.
