### ISSUE TITLE
noVNC // SyntaxError

### ISSUE THREAD

**Issue by Helikipotella** [deconz-community/deconz-docker#255]
Hello,

Thanks in advance for the help and this docker container. 

I have the problem that when I connect to port :6080/vnc.html I get the error "NoVNC encountered an error: SyntaxError: Importing binding name 'initLogging' is not found.".

<img width="566" alt="Bildschirmfoto 2024-07-09 um 16 45 33" src="https://github.com/deconz-community/deconz-docker/assets/81296002/52c94591-2676-425c-9dcd-68eb69b3f029">

Does anyone have an idea how I can fix this? 

Thank you all ☺️

**Comment by senilio** [comment]
Hi,

Never seen that were before :) Do you get the same in another browser?

**Comment by Helikipotella** [comment]
> Hi,
> 
> Never seen that error before :) Do you get the same in another browser?

Wow thanks for that fast reply.

Yes I have this in every browser. 
I also can't find anything similar in the web :D

**Comment by Helikipotella** [comment]
One more thing I noticed is, that I can use the :6080/vnc_lite.html without any issues.

**Comment by senilio** [comment]
Weird. The error message seems to stem from this line in webutils.js (deconz:6080/app/webutil.js)
```
import { initLogging as mainInitLogging } from '../core/util/logging.js';
```

I can't reproduce the error unfortunately. Since JS is executed purely in the web browser, I don't think it's an error in the container image code. Good thing you can use the lite html 👍
