### ISSUE TITLE
Login page - Blank - Login2 works

### ISSUE THREAD

**Issue by istbarp** [deconz-community/deconz-docker#259]
Hi. 

A few updates ago the login page broke.
So if i go to

ip:8081 , then it redirects me to /pwa/login.html

This page is just blank 

![image](https://github.com/user-attachments/assets/6ea85140-a759-4268-b870-e885eb2bd451)

But then if i just replace the 
/pwa/login.html 
with 
/pwa/login2.html then it works and i get the page where i can choose my gateway and such

I'm just using the docker image, nothing fancy in my docker compose.

**Comment by phdelodder** [comment]
@senilio Do you experience the same? 
@Mimiix any previous encounters with this? 
I can't seem to reproduce it.

**Comment by mLgz0rn** [comment]
I got the same issue.
If I remove everything after /pwa/ it will redirect to the correct login page (login2.html)
But when just opening the website http://deconz-website/ it will go to http://deconz-website/pwa/login.html

Gateway Version is 2.27.5 on latest docker branch, 2.27.4 also does it.
The stable docker branch using Gateway Version 2.26.3 does not have this issue.

**Comment by istbarp** [comment]
> I got the same issue. If I remove everything after /pwa/ it will redirect to the correct login page (login2.html) But when just opening the website http://deconz-website/ it will go to http://deconz-website/pwa/login.html
> 
> Gateway Version is 2.27.5 on latest docker branch, 2.27.4 also does it. The stable docker branch using Gateway Version 2.26.3 does not have this issue.

I can confirm, that i also get the same, that if i go to just ip:8081, then it goes to login.html, but if i go to ip:8081/pwa/ then it automatically redirects to the working login2.html.

**Comment by phdelodder** [comment]
This doesn't sound like a issue with the container/docker but more that need to be addressed in the discord/forum or on https://github.com/dresden-elektronik/deconz-rest-plugin/issues

**Comment by skybarberom** [comment]
Having the same problem too. I need to go to manually to login2 to be able to access

**Comment by tom666-debug** [comment]
Same here ... did a fallback to version 2.26.3.

**Comment by istbarp** [comment]
> Same here ... did a fallback to version 2.26.3.

Its honestly not that big of a deal. That i want to roll back features. I just changed my bookmark in the browser to login2.

**Comment by Mimiix** [comment]
https://forum.phoscon.de/t/web-access-not-working/5023/4 Bug report was made (in the correct place) and Phoscon replied.
