### ISSUE TITLE
Issue with Conbee III

### ISSUE THREAD

**Issue by HolgerDoerrschuck** [deconz-community/deconz-docker#264]
Today I did a new installation of deconz on my QNAP diskstation. I did all as described ... baudrade 115200 but I did not find information about the device to be used. It says here:

_Pass the serial device at ttyUSB0 into the container for use by deCONZ (you may need to investigate which device name is assigned to your device depending on if you are also using other usb serial devices; by default ConBee = /dev/ttyUSB0, Conbee II = /dev/ttyACM0, RaspBee = /dev/ttyAMA0 or /dev/ttyS0)._

but there is no information about Conbee III

I tried the Conbee II but it did not work. Honestly I am not sure whether this is to reason. Attached is the log file. Hope someone can help!
[logdeconz.txt](https://github.com/user-attachments/files/16558373/logdeconz.txt)

**Comment by phdelodder** [comment]
Can you check the output of dmesg?

**Comment by HolgerDoerrschuck** [comment]
Hi, will check tomorrow - for today I go back to my Conbee II. I am almost sure that the stick is not working with my Qnap. When I run in a terminal: ls /dev/ I can see the ttyACM0 but when no USB is connected or the new Conbee III there is no difference. The stick in general works whey I use Windows deconz .. Let's see whether I got feedback from Support - or I will send the stick back

**Comment by senilio** [comment]
Does this give any output on your qnap?
```
ls -l /dev/serial/by-id/
```

**Comment by HolgerDoerrschuck** [comment]
I gave the conbee III stick back. As said - the stick works with my Windows computer but not with the QNAP. No idea if this is a QNAP driver issue ...
