### ISSUE TITLE
Incorrect GitHub Repository Link in Docker Hub Documentation

### ISSUE THREAD

**Issue by froido** [deconz-community/deconz-docker#271]
In the documentation on your Docker Hub page (https://hub.docker.com/r/deconzcommunity/deconz), the GitHub repository link under "Issues / Contributing" is incorrect.

It currently says: https://github.com/deconzcommunity/docker-deconz

It should be: https://github.com/deconz-community/deconz-docker/

**Comment by phdelodder** [comment]
Updated
