### ISSUE TITLE
OTA mountpoint?

### ISSUE THREAD

**Issue by gvdhoven** [deconz-community/deconz-docker#32]
In the old image i had a mountpoint towards `/root/otau` for the OTA firmware images. Is this now changed to `/opt/otau`? and if so, can you update the documentation (readme) for this?

Update:
I see in the repository that the OTA path is: `/opt/deCONZ/otau`
No separate volume mapping seems to be needed, right?

**Comment by phdelodder** [comment]
no seperate volume required, the path is `/opt/deCONZ/otau`
