### ISSUE TITLE
Permission problem after upgrading Debian 10 to 11

### ISSUE THREAD

**Issue by cschillings** [deconz-community/deconz-docker#41]
Goodevening.

After i upgraded my system to Debian 11 Bullseye i got a permission error, before the upgrade everything works oke with the same settings
Hopefully someone can tell me what is going wrong.
<pre>
+ echo [deconzcommunity/deconz] Starting deCONZ...

+ echo [deconzcommunity/deconz] Current deCONZ version: 2.13.02

+ echo [deconzcommunity/deconz] Web UI port: 8002

+ echo [deconzcommunity/deconz] Websockets port: 8003

+ DECONZ_OPTS=--auto-connect=1         --appdata=/opt/deCONZ         --dbg-info=1         --dbg-aps=0         --dbg-zcl=0         --dbg-zdp=0         --dbg-otau=0 	--dbg-error=0         --http-port=8002         --ws-port=8003

+ echo [deconzcommunity/deconz] Modifying user and group ID

+ [ 0 != 1000 ]

[deconzcommunity/deconz] Starting deCONZ...

[deconzcommunity/deconz] Current deCONZ version: 2.13.02

[deconzcommunity/deconz] Web UI port: 8002

[deconzcommunity/deconz] Websockets port: 8003

[deconzcommunity/deconz] Modifying user and group ID

+ DECONZ_UID=0

+ sudo usermod -o -u 0 deconz

+ [ 0 != 1000 ]

+ DECONZ_GID=0

+ sudo groupmod -o -g 0 deconz

[deconzcommunity/deconz] Checking device group ID

+ echo [deconzcommunity/deconz] Checking device group ID
      
+ [ 0 != 0 ]

+ [ -e /dev/ttyUSB0 ]

+ [ -e /dev/ttyACM0 ]

+ [ -e /dev/ttyAMA0 ]

+ [ -e /dev/ttyS0 ]

+ stat --printf=%g

<b>stat: missing operand</b>

Try 'stat --help' for more information.

+ DIALOUTGROUPID=

+ DIALOUTGROUPID=20

+ [ 20 != 20 ]
      
+ stat -c %A
      
+ cut -c 5-7

<b>stat: missing operand</b>

Try 'stat --help' for more information.

+ GROUPPERMISSIONS=
      
+ [  = --- ]
      
+ [ 1 != 0 ]

22:13:52:091 dev can't create file: /dev/ttyACM0 via mknod (missing permissions)

22:13:53:094 dev can't create file: /dev/ttyACM0 via mknod (missing permissions)

22:13:56:079 dev can't create file: /dev/ttyACM0 via mknod (missing permissions)
</pre>

<pre>
version: "3.9"
services:
  deconz:
    image: deconzcommunity/deconz
    container_name: deconz
    restart: always
    network_mode: host
    volumes:
      - /opt/deconz:/opt/deCONZ
      - /run/udev:/run/udev:ro
    device_cgroup_rules:
      - 'c 166:* rmw' # allow creation of /dev/ttyACMx nodes via mknod
      - 'c 188:* rmw' # allow creation of /dev/ttyUSBx nodes via mknod
    devices:
      - /dev/bus/usb
    environment:
      - TZ=Europe/Amsterdam
      - DECONZ_UID=0
      - DECONZ_GID=0
      - DECONZ_START_VERBOSE=1
      - DECONZ_WEB_PORT=8002
      - DECONZ_WS_PORT=8003
      - DECONZ_VNC_MODE=1
      - DECONZ_VNC_PORT=8004
      - DECONZ_VNC_PASSWORD=xxxx
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0
</pre>

**Comment by cschillings** [comment]
This was the solution, takes me the whole evening to find this...

<pre>
    volumes:
      - /opt/deconz:/opt/deCONZ
      - /run/udev:/run/udev:ro
      <b>- /dev:/dev</b>
</pre>

**Comment by Tin-Bui** [comment]
Adding dev volume didn't help me.
I added the correct device to my setup as followed:
  deconz:
    image: deconzcommunity/deconz:latest
    container_name: deconz
    devices:
      **- /dev/ttyACM0**

And successfully pair my new IKEA remotes.
Note: I also made sure the DECONZ_UID belong to the dialout group, as per [pre-requisite](https://github.com/deconz-community/deconz-docker#pre-requisite)

**Comment by phdelodder** [comment]
@Tin-Bui Please share you full compose file and the log with deconz_debug enabled. I would recommend to create a new ticket.
