### ISSUE TITLE
doconz fails after pushing certain switch buttons

### ISSUE THREAD

**Issue by doets001** [deconz-community/deconz-docker#42]
I think it is a deconz issue....
I'm using a setup with a conbee II and deconz running in a docker container. Then I run home assistant, also in a docker container. 

home assistant : homeassistant/home-assistant:2021.10.5
I use the deCONZ integration to do some more automations on the zeebe device. I do not do any automation on the mentioned switch below.

deconz docker image : deconzcommunity/deconz:2.13.02
conbee II:
Version : 2.13.02 / 10/11/2021
Firmware : 26720700

Switch:
Vendor IKEA of Sweden
Product STYRBAR
Version 1.0.024

I bought some new Ikea switches where I encountered the following issue. When I configure the first two buttons with "dimming up and on" and "dimming down and off" it works as expected.
<img width="738" alt="Screenshot 2021-11-28 at 18 50 09" src="https://user-images.githubusercontent.com/49761576/143779827-45c9ef86-db19-4174-9c67-425e200ccf93.png">

When I configure the next two buttons for changing the color temperature warmer and colder it does not work. After using these 3th and 4th button it also make the 1th and 2nd fail to respond. I see messages like "skip binding for attribute reporting of ep: 0x00 cluster 0x1000 (end-device might sleep)". 

After restarting the deconz container the first two buttons work fine again.

**Comment by senilio** [comment]
This repo is only about the docker container, not with phoscon or deCONZ. Pls create a new issue in a more suitable repo.

**Comment by doets001** [comment]
oke, sorry...
