### ISSUE TITLE
'device' unable to be set as /dev/serial/by-id/xxxxxx

### ISSUE THREAD

**Issue by asktimfisher** [deconz-community/deconz-docker#44]
The 'device' parameter can be set as /dev/ttyACM0 (for example) but can't be set as /dev/serial/by-id/xxxxxx. The by-id never changes but the /dev/tty does, causing lots of problems on reboots.

No error and the docker run completes successfully but then it's clear in the Phoscon gateway settings that something is wrong.

Happy to provide screenshots or other information if needed.

**Comment by senilio** [comment]
Hi, this is an issue with deCONZ... the way I'm working around it is passing the by-id device as ttyACM0, like this:

```
    devices:
      - /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE1234567-if00:/dev/ttyACM0
```

That way the container only sees ttyACM0, and we're still immune to changing device names at reboot.

**Comment by asktimfisher** [comment]
Thanks for this! Still having issues, however. My Conbee device is currently running at ttyACM1 and so I ran this:

`docker run -d --name=zigbee --net=host --restart unless-stopped -e PUID=1000 -e PGID=1000 -e DECONZ_DEVICE=/dev/ttyACM1 -e DECONZ_WEB_PORT=7100 -e DECONZ_WS_PORT=7101 -e DECONZ_VNC_MODE=1 -e DECONZ_VNC_PORT=7102 -e DECONZ_VNC_PASSWORD=Sw374ACu -e TZ=America/Denver -v /home/home/zigbee:/opt/deCONZ --device=/dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2234405-if00:/dev/ttyACM1 deconzcommunity/deconz'

And my gateway reports "Not connected" as the Firmware and I lose control of all the lights.

Thoughts? What am I doing wrong?

**Comment by senilio** [comment]
Even though the device name is ttyACM1 on your host, you should still forward present it as ttyACM0 to the container. At least this is what I think is the problem.

**Comment by asktimfisher** [comment]
This worked like a charm! Thank you!!
