### ISSUE TITLE
Hue Wall Switch Modul integration is missing

### ISSUE THREAD

**Issue by m4d-maNu** [deconz-community/deconz-docker#50]
Hi, 
the Hue Wall Switch Modul integration is missing in the deconz-docker.  

https://github.com/dresden-elektronik/deconz-rest-plugin/releases/tag/v2.12.2-beta

Can integrate this?

**Comment by senilio** [comment]
This container only runs the deconz releases as is. If something is missing from deCONZ or Phoscon it's not due to docker or this image. If you think that something is missing from deCONZ, please open an issue in the appropriate repo.
