### ISSUE TITLE
Pairing Aqara Smart Wireless Switch WXKG11LM

### ISSUE THREAD

**Issue by nielsras** [deconz-community/deconz-docker#53]
Hello,

Unfortunately I'm not able to pair it in the Phoscon App.

Produkt: ConBee II
Firmware: 26720700

Deconz VNC shows it's connected. 
![2021-12-16  Deconz](https://user-images.githubusercontent.com/74150297/146401394-adf25e18-1672-40f0-acc7-63ccb5f2921d.png)
![2021-12-16  Deconz  2](https://user-images.githubusercontent.com/74150297/146401831-8914f762-86fa-4612-9ac5-8e22e219e0fe.png)

Other Aqara sensors connects without any problem. 

Does anyone have a useful tip for me?

Thanks in advance!

**Comment by phdelodder** [comment]
@nielsras I think you need to checkout https://github.com/dresden-elektronik/deconz-rest-plugin

**Comment by senilio** [comment]
Closing, as this is unrelated to docker.
