### ISSUE TITLE
No config files written? (Synology NAS DSM7)

### ISSUE THREAD

**Issue by pixelwave** [deconz-community/deconz-docker#55]
Hi,

I put everything together and it works on my Synology DS918+ perfectly together with Homeassistant (Docker) and Conbee II. The only issue I have is that the deconz folder is empty? And sometimes when I update the deconz docker image via watchtower it loses all the configuration and I have to re-setup the conbee II. 

I assume there is an issue with the volume mounted to the deconz docker or the config?

<img width="526" alt="Bildschirmfoto 2021-12-18 um 13 07 20" src="https://user-images.githubusercontent.com/19491804/146640547-9f14343d-68f3-4f19-96df-9d668eb2c7ca.png">
<img width="627" alt="Bildschirmfoto 2021-12-18 um 13 07 33" src="https://user-images.githubusercontent.com/19491804/146640549-ee6aef57-1403-4762-b1af-07c836aabd7f.png">

**Comment by phdelodder** [comment]
The path is case sensitive, so it's /opt/deCONZ you should use.

**Comment by pixelwave** [comment]
thanks ... now it works. :)
