### ISSUE TITLE
wiringpi not available any longer

### ISSUE THREAD

**Issue by ralhei** [deconz-community/deconz-docker#60]
Hi, 
the README states that `wiringpi` should be installed for a RaspBee/Raspbee 2 installation on a Raspberry PI 4B.

However raspberry pi OS does not provide this package any longer. Furthermore the wiringpi git repo has been shutdown after this project was deprecated in late 2019. 

So, can this recommendation just be skipped? Or is there an alternative that needs to be installed instead?

Cheers,
Ralph

**Comment by phdelodder** [comment]
You can try without installing it and see works?

**Comment by ralhei** [comment]
I indeed tried it without wiringpi, and yes, it didn't work, my raspbee did not show up in the phoscon ui. 

However I'm a bit surprised that a library like wiringpi must be installed in the host OS to the the software inside a docker container to work. Normally the OS inside the container should not be able to access libraries and executables of the hosting OS, or am I wrong?

**Comment by phdelodder** [comment]
@manup can you shed some light on this?

**Comment by gsx95** [comment]
Hi @ralhei,
I had the same problem, but you can just download the latest release of wiringpi here 
http://wiringpi.com/wiringpi-updated-to-2-52-for-the-raspberry-pi-4b/

Hope it helps, my raspbee is working fine now :)

**Comment by ralhei** [comment]
Just a quick question, before I setup my raspberry again: did you install this debian package INSIDE the docker container? Or directly on the raspberry that runs docker? The latter option sounds weird to me, for the reasons described above. But well, if that is the solution ... the solution always wins ;-)

**Comment by gsx95** [comment]
Yep I installed it on the raspberry, not inside the docker container. Not sure why that's needed though, but it works 🤷‍♂️

**Comment by senilio** [comment]
Case closed

**Comment by Philip-A** [comment]
why is it closed? what is the solution?

**Comment by manup** [comment]
I have this on my todo list, the docs need to be updated. WiringPi is no longer a required dependency as GCFFlasher can reboot the MCU also by serial command. In rare cases where this doesn't work the hard method of unplug/reattach while GCFFlasher is running with -t 60 also works.

The next version of GCFFlasher 4.x uses optionally the Linux standard library *gpoid* as replacement for WiringPi, this isn't yet part of the deCONZ package but could be tested: https://github.com/dresden-elektronik/gcfflasher

**Comment by senilio** [comment]
> why is it closed? what is the solution?

The solution is to install wiringpi. See https://github.com/deconz-community/deconz-docker/issues/60#issuecomment-1018740348
