### ISSUE TITLE
Cannot start service deconz: error gathering device information while adding custom device "/dev/ttyUSB0": no such file or directory

### ISSUE THREAD

**Issue by antgustech** [deconz-community/deconz-docker#63]
I'm completely new to this but I recently got my Conbee II stick working by using the now deprecated marthoc/docker-deconz image. Then I found this community managed image instead so I thought I should use this instead. However upon creating the container, it fails, it cannot detect my USB device:

```
`Removing deconz
Recreating 4d156e7a16da_deconz ... error

ERROR: for 4d156e7a16da_deconz  Cannot start service deconz: error gathering device information while adding custom device "/dev/ttyUSB0": no such file or directory

ERROR: for deconz  Cannot start service deconz: error gathering device information while adding custom device "/dev/ttyUSB0": no such file or directory
ERROR: Encountered errors while bringing up the project.`
```

I did run the `sudo usermod -a -G dialout $USER ` command.

Again, I did not experience this problem with the old image.

I might also add that the only thing I changed in the docker-compose file is the ports as I am also running pi hole as a docker container.

```
version: "2"
services:
  deconz:
    image: deconzcommunity/deconz:stable
    container_name: deconz
    restart: always
    ports: 
      - 80:80
      - 443:443
    volumes:
      - /opt/deconz:/opt/deCONZ
    devices:
      - /dev/ttyUSB0
    environment:
      - DECONZ_WEB_PORT=80
      - DECONZ_WS_PORT=443
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0
```

**Comment by senilio** [comment]
Is the conbee 2 actually named /dev/ttyUSB0 in your host OS?

**Comment by antgustech** [comment]
No, I just read from the docs that it should be `/dev/ttyACM0` Conbee II! Now it works.
