### ISSUE TITLE
Cannot Edit Multisensor

### ISSUE THREAD

**Issue by bennyryan** [deconz-community/deconz-docker#65]
Running the docker instance.
Cannot edit 2 of my new sensors but can on my third.

There are reported errors in the console on the Sensors screen.

- Uncaught TypeError: sg is null
- Firefox can’t establish a connection to the server at ws://192.168.86.200:443/.
- Uncaught TypeError: this.versionLabel is undefined

![Connected Sensors](https://user-images.githubusercontent.com/7296570/147716820-96aecabe-f837-416c-b83e-475553258e39.jpg)

**Comment by senilio** [comment]
Being unable to edit sensors in Phoscon is unrelated to the docker image. You're probably looking for the Phoscon repo https://github.com/dresden-elektronik/phoscon-app-beta or the forum https://forum.phoscon.de/
