### ISSUE TITLE
Debug options typo

### ISSUE THREAD

**Issue by duffbeer2000** [deconz-community/deconz-docker#66]
I think there is a typo in the start.sh:
DECONZ_OPTS="--auto-connect=1 \
        --appdata=/opt/deCONZ \
        --dbg-info=$DEBUG_INFO \
        --dbg-aps=$DEBUG_APS \
        --dbg-zcl=$DEBUG_ZCL \
        --dbg-zdp=$DEBUG_ZDP \
        **--dbg-otau=$DEBUG_OTAU** \
	--dbg-error=$DEBUG_ERROR \
        --http-port=$DECONZ_WEB_PORT \
        --ws-port=$DECONZ_WS_PORT"

If you look here: https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/deCONZ-debug-flags
the option for ota debug should be: dbg-ota
Maybe it should be changed to: **--dbg-ota=$DEBUG_OTA**

**Comment by phdelodder** [comment]
Indeed this needs to be fixed
