### ISSUE TITLE
help with cgroups

### ISSUE THREAD

**Issue by Smeds** [deconz-community/deconz-docker#74]
Using marthoc/deconz I was able to include usb devices using cgroup rules, ex

```
device_cgroup_rules:
  - 'c 188:* rmw'
```

but with the deconzcommunity/deconz I have no success.

Does anyone have any suggestion of how to make cgroup rules work?

Using the devices option I'm able to access my usb device but the problem
with this solution is that sometimes the ttyUSB[ID] changes.

**Comment by senilio** [comment]
Do you have a `/dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DExxxxxxxx-if00` device on your host? That should never change. If so, forward it to the container like this:

```
    devices:
      - /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DExxxxxxxx-if00:/dev/ttyACM0
```

**Comment by thijsputman** [comment]
There indeed appears to be somewhat of regression here...

@Smeds, with the below configuration, the `cgroups` setup works for me. It's based on what was originally mentioned in https://github.com/marthoc/docker-deconz/issues/298 (sadly a dead link now).

```yaml
volumes:
  - /run/udev:/run/udev:ro
device_cgroup_rules:
  - 'c 166:* rmw'
  - 'c 188:* rmw'
devices:
   - /dev/bus/usb
```

There's one _major_ caveat: With this setup, the deCONZ GUI (via VNC) can't find/connect to the ConBee stick and just shows an empty screen (the "Phoscon App" works fine though). Appears related to these errors while starting the container:

```log
[deconzcommunity/deconz] Modifying user and group ID
[deconzcommunity/deconz] Checking device group ID
stat: missing operand
Try 'stat --help' for more information.
stat: missing operand
Try 'stat --help' for more information.
[deconzcommunity/deconz] VNC port: 5990
```

The configuration proposed by @senilio is a good workaround for now.

As far as I understand how thinks work on the Docker end, it has one drawback: With a hard-coded device mapping, hotplugging (i.e. unplug, plug back in) doesn't work. You need to restart the Docker container; with the `cgroups` approach, hotplugging is possible.

**Comment by lhurt** [comment]
Came across this issue and wanted to share my solution.

My installation uses udev to create the symbolic link (/dev/ttyUSB_ConBeeII) based on the serial number of the stick. This provides independence of the port and however the stick is automatically handled elsewhere.

You can get your serial using this command
```
$ lsusb -vd 1cf1: | grep -i serial
can't get debug descriptor: Resource temporarily unavailable
  iSerial                 3 DE1234567
          line coding and serial state
```

Then you can create the file /etc/udev/rules.d/10-usb-serial.rules 
`SUBSYSTEM=="tty",SUBSYSTEMS=="usb",DRIVERS=="usb",ATTRS{serial}=="DE1234567", SYMLINK+="ttyUSB_ConBeeII", MODE="0666"
`
Please make sure to **change the serial number** according to your stick.

My docker-compose contains these lines:
```
...
    devices:
      - /dev/ttyUSB_ConBeeII:/dev/ttyACM0
    volumes:
      - ./deCONZ:/opt/deCONZ
      - /run/udev:/run/udev:ro  # so that serial number vendor/product ids are known
...
```

The last line (/run/udev:/run/udev:ro) is not mentioned in the docs but required to enable access to the serial number of the Conbee Stick within the container. The difference can be seen in the log.

without /run/udev:/run/udev:ro
`09:36:35:712 COM: /dev/ttyACM0 / serialno: , ConBee II`

with /run/udev:/run/udev:ro
`09:38:08:701 COM: /dev/ttyACM0 / serialno: DE1234567, ConBee II
`

Hope that helps.

**Comment by senilio** [comment]
Thanks @thijsputman and @lhurt for the input! Will use it for improving the documentation.
