### ISSUE TITLE
high cpu usage

### ISSUE THREAD

**Issue by javiges** [deconz-community/deconz-docker#76]
Since I updated to the latest version, the cpu load has risen from 6% to 13% at rest, I have gone down to version 2.12.06 and the cpu went down to its normal state, it has already happened to me in several versions and not I know where the problem is

**Comment by senilio** [comment]
Which process is generating the increased CPU load? is it deCONZ or something else?

**Comment by javiges** [comment]
when doing a htop it is always at the top, it had already happened to me in other updates, what I did was go down to 2.13.01 and return to normal

**Comment by senilio** [comment]
If the deCONZ process is running high on CPU, that is not likely related to the this docker image. It just runs the latest release of the deCONZ found here https://deconz.dresden-elektronik.de/

I think you're better off opening a new topic on the forum (forums.phoscon.de) or on the deCONZ repo.
