### ISSUE TITLE
Unable to load deconz webUI using docker image

### ISSUE THREAD

**Issue by jpverkamp** [deconz-community/deconz-docker#84]
Hello, I have tried to bring up the deconz-community/deconz-docker image on my local system and it appears to be finding my device (a Conbee II), but I'm not able to load the webUI.

docker-compose.yml:

```yaml
version: "3.8"

services:
   ...

  deconz:
    container_name: deconz
    restart: always
    expose:
      - 8190
      - 8191
    volumes:
      - "/home/jp/Projects/server/deconz:/opt/deCONZ"
    environment:
      TZ: America/Indianapolis
      DECONZ_UID: 1000
      DECONZ_GID: 1000
      DECONZ_DEVICE: /dev/ttyACM0
      DECONZ_WEB_PORT: 8190
      DECONZ_WS_PORT: 8191
      DECONZ_UPNP: 0
    devices:
      - /dev/ttyACM0
    image: deconzcommunity/deconz:stable
```

I am running behind nginx proxy manager. 

I've tried with default ports (80/443, 8190/8191, 8190/8190) and various other options (enabling/disabling the `expose` section), but nothing seems to change this behavior. Running `curl` within the container returns the same thing. I even tried `network_mode: "host"`, directly exposing it to my local network without any luck. 

I did also enable the VNC functionality and the noVNC port and in both cases, that *did* work, so I was able to see my local setup with that, but the webUI still did not load so I turned that off for the moment. 

Logs:

```text
deconz                    | [deconzcommunity/deconz] Starting deCONZ...
deconz                    | [deconzcommunity/deconz] Current deCONZ version: 2.14.01
deconz                    | [deconzcommunity/deconz] Web UI port: 8190
deconz                    | [deconzcommunity/deconz] Websockets port: 8191
deconz                    | [deconzcommunity/deconz] Modifying user and group ID
deconz                    | [deconzcommunity/deconz] Checking device group ID
deconz                    | [deconzcommunity/deconz] VNC Disabled
deconz                    | QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-deconz'
deconz                    | QStandardPaths: wrong ownership on runtime directory /tmp/runtime-deconz, -2 instead of 1000
deconz                    | libpng warning: iCCP: known incorrect sRGB profile
deconz                    | This plugin does not support propagateSizeHints()
deconz                    | This plugin does not support propagateSizeHints()
deconz                    | 21:19:30:492 HTTP Server listen on address 0.0.0.0, port: 8190, root: /usr/share/deCONZ/webapp/
deconz                    | 21:19:30:526 dev can't create file: /dev/ttyUSB0 via mknod (missing permissions)
deconz                    | 21:19:30:526 COM: /dev/ttyACM0 / serialno: , ConBee II
deconz                    | 21:19:30:526 ZCLDB init file /opt/deCONZ/zcldb.txt
deconz                    | 21:19:30:543 /usr/bin/../share/deCONZ/plugins no plugin directory found
deconz                    | 21:19:31:571 dev can't create file: /dev/ttyUSB0 via mknod (missing permissions)
deconz                    | 21:19:31:571 COM: /dev/ttyACM0 / serialno: , ConBee II
deconz                    | This plugin does not support propagateSizeHints()
deconz                    | 21:19:33:020 Device firmware version 0x26580700 ConBee II
deconz                    | 21:19:33:021 unlocked max nodes: 512
deconz                    | 21:19:33:039 Device protocol version: 0x010B
deconz                    | 21:19:33:043 new node - ext: 0x00212effff07bf6b, nwk: 0x0000
deconz                    | 21:19:33:056 Current channel 15
deconz                    | 21:19:33:060 CTRL ANT_CTRL 0x03
deconz                    | 21:19:33:069 Device protocol version: 0x010B
deconz                    | 21:19:33:087 CTRL ANT_CTRL 0x03
deconz                    | 21:19:44:496 saved node state in 0 ms
deconz                    | 21:19:44:496 sync() in 0 ms
```

So it does appear to be properly listening on port 8190 with the correct root directory (it exists when looking inside the container), but when I load the page, I get as a response a `404` with:

```text
This is not the page you are looking for

The file / couldn't be found.
```

I've tried the `latest`, `stable`, `beta`, `2.13.04`, and `2.12.06` images as well without luck. 

My one current guess was [this blog post](https://www.cbroderick.me/blog/2021/07/30/updating-deconz-docker/) which suggested that the change to Debian slim might be involved? I tried rebuilding the image locally first just changing the `FROM` line which failed due to a missing Qt library.

Build command:

```text
docker build --build-arg VERSION=2.14.01 --build-arg CHANNEL=stable --build-arg TARGETPLATFORM=amd64 -t "jp/deconz:local" ./docker/
```

Changed the image to `jp/deconz:local` in my docker-compose.yml. 

Second try here was replacing the entire Dockerfile with the one from the blog post, but that no longer builds (same error).

```text
Unpacking deconz (2.14.01-ubuntu-bionic-stable) ...
dpkg: dependency problems prevent configuration of deconz:
 deconz depends on libqt5qml5; however:
  Package libqt5qml5 is not installed.

dpkg: error processing package deconz (--install):
 dependency problems - leaving unconfigured
Processing triggers for mime-support (3.60) ...
Errors were encountered while processing:
 deconz
```

So... at the moment, I'm at a loss to getting this working. Any help would be appreciated.

**Comment by sknsean** [comment]
+1 works with the marthoc/deconz image...

This image:
`[deconzcommunity/deconz] Web UI port: 480`

marthoc/deconz:
```
[marthoc/deconz] Web UI port: 480
13:34:26:992 HTTP Server listen on address 0.0.0.0, port: 480
```

**Comment by sknsean** [comment]
Forget my run lines
```
docker run -d \
    --name=deconz \
    --restart=always \
    --net=bridge \
     -p 480:480 \
    -p 4443:4443 \
    -p 5900:5900 \
    -e TZ=Europe/Copenhagen \
    -e DECONZ_WEB_PORT=480 \
    -e DECONZ_WS_PORT=4443 \
    -e DECONZ_VNC_MODE=1 \
    -e DECONZ_VNC_PORT=5900 \
    -v /volume1/docker/deconz:/opt/deCONZ \
    --device=/dev/ttyACM0 \
    deconzcommunity/deconz
```

```
docker run -d \
    --name=deconz \
    --restart=always \
    --net=bridge \
     -p 480:480 \
    -p 4443:4443 \
    -p 5900:5900 \
    -e TZ=Europe/Copenhagen \
    -e DECONZ_WEB_PORT=480 \
    -e DECONZ_WS_PORT=4443 \
    -e DECONZ_VNC_MODE=1 \
    -e DECONZ_VNC_PORT=5900 \
    -v /volume1/docker/deconz:/root/.local/share/dresden-elektronik/deCONZ \
    --device=/dev/ttyACM0 \
    marthoc/deconz
```

**Comment by sknsean** [comment]
@jpverkamp sorry for the hijack, but I'm sure it's related what we are seeing...

@phdelodder `ss -tapn` and `netstat -tapn` shows nothing is listening on the web port

**Comment by jpverkamp** [comment]
Might be related, but I don't think it's the same issue. 

In my case, the web server prints that it's launching, I can see it listening with netstat, and I can make requests to it either inside the container or outside of it, I'm just not returned anything useful.

**Comment by phdelodder** [comment]
@sknsean I think it's better you create your own issue. please do also provide logs!

@jpverkamp Have you tried with mounting an empty volume/dir, so that it doesn't take your config from marthoc? I also understand you test in combination with a reverse proxy, have tried taken that out of the picture first?

**Comment by jpverkamp** [comment]
Removing the volume had the same symptoms (`no plugin directory found` + `404 This is not the page you are looking for`). 

I did try both mapping the ports (a la `80:80` / `8190:8190`) and `network_mode: host`. Both did the same thing. I have also tried running directly with `docker run` rather than `docker-compose`, same thing. 

I am not migrating from marthoc, this is the first time I'm trying to bring up deCONZ. I hadn't actually tried using the older `marthoc/deconz` image before. That also doesn't work (with the same problem), so I suppose it's an older issue.

**Comment by jpverkamp** [comment]
Potential finding:

I am running into this issue on an `amd64` device (linux server). Running it in docker on an M1 Mac (`arm64`) with a minimal `docker run` command (just the ports, no devices), works fine, webUI loads. Albeit not entirely functional because I don't have the ConBee II on that device. 

I haven't moved the ConBee II over to that machine yet (and don't want to rely on that permanently), but I can try that in the morning. Just in case, I did try not mapping the `devices` on the Linux machine, that did not help.

**Comment by phdelodder** [comment]
Could then provide the full log with `DECONZ_START_VERBOSE=1` added? I noticed that you didn't set the `DECONZ_UID` en `DECONZ_GID`, you could add them 0 (running as root)

**Comment by xxLeoxx93** [comment]
+ 1, also struggling to get it running on a raspberry pi bullseye 64 Bit.
Tried to many things to list here but now I know I'm not the only one with this issue :)
Not sure if it helps but my log gets filled with this line over and over again:
"20:43:05:923 remove discovery request duplicate"

**Comment by realgir** [comment]
also have the same problem, cant access web ui. Moved from marthoc/docker-deconz. All zigbee units are reachable and working.  Booted up a new deconz parallell to my main. If i browse the new deconz web,  both old and new deconz shows up, and both are reachable through the new ip.

![image](https://user-images.githubusercontent.com/53936257/155285008-65860926-3c7f-4ad8-aa87-d08c0c26ecfd.png)

**Comment by axtrim** [comment]
Hi.
I'm running the docker Image on a Synology DiskStation and migrated them from marthoc/deconz. The same error occurs every time when starting. curl tries again and again to call the 127.0.0.1 on port 80 but does not reach it. At least not as long as the default port 80 is set for the webui. If I change the port to 8080 the container starts normally.
No matter which environment variables I use, the default port in the config.ini in the folder /opt/deCONZ under the item [remote] is always changed to port 8080 at startup. Even editing it manually to port 80 does not change anything, the port 8080 is automatically entered again at startup.
Maybe my findings contribute to the solution. 
phoscon runs under 8080 but the missing Alexa access is a bit annoying.

**Comment by jpverkamp** [comment]
I still have had no issue with the docker image loading (always the same default page loading instead of any web UI). I tried [ZHA](https://www.home-assistant.io/integrations/zha/) directly in Home Assistant and it worked first try, so I'm going to use that instead. 

Thanks for any help, but I'm going to close this issue now. Feel free to re-open or open a similar issue and ping me if someone else has the same problem.
