### ISSUE TITLE
Run on Pi Zero W (v1)?

### ISSUE THREAD

**Issue by chetbox** [deconz-community/deconz-docker#88]
Hi! Is it possible to run this on a Pi Zero W (v1)? Docker complains that it's expecting a `linux/arm/v6` but only `linux/arm/v7` seems to be available [on Docker Hub](https://hub.docker.com/r/deconzcommunity/deconz/tags).

I'm using Rasbian 11 (Bullseye) with a Raspbee II on a Raspberry Pi Zero W V1.1.

**Comment by phdelodder** [comment]
There is no arm v6 build available for docker.

**Comment by MattL0** [comment]
Off topic sorry.

I would be very curious to see how a rasbee II physically attached to a raspberry pi zero W if you have the time to send a picture. @chetbox

**Comment by chetbox** [comment]
![IMG_0168](https://user-images.githubusercontent.com/292958/157424806-91790528-4cf4-4fe0-bf44-e9bf2e9fe56f.jpg)

Is there any reason deconz can't be run on arm v6? I'm wondering if [this script](https://github.com/deconz-community/deconz-docker/blob/main/docker/download-deconz.sh) supported arm v6 would there be any stumbling blocks I should be aware of?

**Comment by phdelodder** [comment]
The script extending is not an issue, also the entire docker build process needs to be extended. 

@manup is arm v6 supported as a deb package?

**Comment by Jo-Be-Co** [comment]
@phdelodder if you are considering to extend [the script](https://github.com/deconz-community/deconz-docker/blob/main/docker/download-deconz.sh) you should also get rid of all the `grep` calls.
1. there is not really a pattern involved
2. The option -E (for extended patterns) makes the tool even bigger 🤓 
3. bash can check this on it's own:
```bash
case "${PLATFORM}" in
  *arm64*)
    URL="..."
    ;;
  *amd64*)
    URL="..."
    ;;
  *v7*)
    URL="..."
    ;;
esac
```
And if needed the pattern could be more complex: [pattern matching in bash](https://www.gnu.org/software/bash/manual/html_node/Pattern-Matching.html#Pattern-Matching)

**Comment by manup** [comment]
The package should work on the Pi Zero, there are quite some installations running on it :)

**Comment by chetbox** [comment]
This might be a silly question but what do I have to do to test it? Where do I find the Docker image?

**Comment by phdelodder** [comment]
The build fails. You can check the PR.

**Comment by phdelodder** [comment]
Have you tried with the docker armhf build?

**Comment by rugarci** [comment]
Trying to build directly in a Raspberry Pi Zero W (v1.1) with:
`
docker build -t deconz --build-arg BUILDPLATFORM=linux/arm/v6 --build-arg TARGETPLATFORM=linux/arm/v6 --build-arg CHANNEL=stable --build-arg VERSION=2.16.01 .
`

fails with:

The following packages have unmet dependencies:
 deconz:armhf : Depends: libqt5core5a:armhf but it is not installable
                Depends: libqt5network5:armhf but it is not installable
                Depends: libqt5widgets5:armhf but it is not installable
                Depends: libqt5gui5:armhf but it is not installable
                Depends: libqt5serialport5:armhf but it is not installable
                Depends: libqt5websockets5:armhf but it is not installable
                Depends: libqt5sql5:armhf but it is not installable
                Depends: libqt5qml5:armhf but it is not installable
                Depends: lsof:armhf but it is not installable
E: Unable to correct problems, you have held broken packages.
The command '/bin/sh -c apt install /deconz.deb &&     chown root:root /usr/bin/deCONZ* &&     setcap

**Comment by rugarci** [comment]
I was able to build the image with 
```
RUN apt-get update && \
    apt-get install -y \
	gosu \
        curl \
        kmod \
	libatomic1 \
        libcap2-bin \
        libqt5core5a:armhf \
        libqt5gui5:armhf  \
        libqt5network5:armhf  \
        libqt5serialport5:armhf  \
        libqt5sql5:armhf  \
        libqt5websockets5:armhf  \
        libqt5widgets5:armhf  \
	libqt5qml5:armhf  \
        libssl1.1 \
        lsof:armhf  \
        sqlite3 \
        tigervnc-standalone-server \
        tigervnc-common \
        novnc \
        websockify \
        openbox \
        xfonts-base \
        xfonts-scalable && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
```

But now the image fails on bootstrap:

```
[deconzcommunity/deconz] Starting deCONZ...
[deconzcommunity/deconz] Current deCONZ version: 2.16.01
[deconzcommunity/deconz] Web UI port: 8083
[deconzcommunity/deconz] Websockets port: 8443
[deconzcommunity/deconz] Modifying user and group ID
[deconzcommunity/deconz] Checking device group ID
[deconzcommunity/deconz] VNC Disabled
```

I already set DEBUG_INFO=2 and DEBUG_ERROR=2. Any idea how to debug farther?

**Comment by senilio** [comment]
I think we can safely assume that this architecture is not nor will be supported by Dresden Elektronik. We've asked for it but I'm afraid it's very low priority.
