### ISSUE TITLE
deCONZ @ QNAP Container Station

### ISSUE THREAD

**Issue by SkipperDo** [deconz-community/deconz-docker#89]
Hi

Today i needed to Update the QNAP Container Station to Version V2.5.0.312 on my QNAP TS-453A Firmware Version: 5.0.0.1932 because i get following Message:
[App Center] The app digital signature has expired: Container Station

After updating the created deCONZ container crashes at startup with following error message:
500 Server Error: Internal Server Error ("execute qnetwork-tool [vswitch get --physical_nic bond0] failed: Error: strconv.Atoi: parsing "": invalid syntax ")

The Container Log shows following:
<nothing>

a Downgrade of the Container Station looks impossible...

Currently nothing works..
I Need some help...

Any Ideas to fix it?

i Have some other Containers running in the Container Station (e.g. HomeAssistant, Watchtower, ESPHome) only the deCONZ and the NodeRed Container are effected by this issue...

**Comment by phdelodder** [comment]
This seems more related to qnap it self. can 't help you on that one.

**Comment by SkipperDo** [comment]
Yeah... Phoscon Problem solved... Just forget port forwarding in the NAT Settings for the Phoscon Web App... 😅
