### ISSUE TITLE
Automatic download ZigBee Firmware every x days...

### ISSUE THREAD

**Issue by SkipperDo** [deconz-community/deconz-docker#91]
Hi..

I Currently mostly use IKEA Zigbee Hardware at Home...
Dresden Electronik pubilshes a python script to download & save the IKEA Zigbee Firmware local and flash the Devices...

Is it possible to add crontab in this Docker Image? So crontab execute this script every x days & check for new Firmware & download it?
This would be a cool Feature...

Kind regards...

**Comment by phdelodder** [comment]
Not something that I plan to do, I'm happy to merge it when you got it working ;-)

**Comment by SkipperDo** [comment]
Ok I will try it...

Can you tell me the distro deConz running on in this Container?

**Comment by phdelodder** [comment]
It's running debian

**Comment by Jo-Be-Co** [comment]
Thanks. I really have to dive into this feature!

So, what about using a host folder for the otau files? You could add one folder of your choice to the container config or as parameter `-v /abc/myOTAU:/root/otau`.
Then you have access to the storage and scheduling any kind of update is also done from "outside".

**Comment by Jo-Be-Co** [comment]
This would also harden against loss of firmware files. If all is stored inside your container you'll have to download all files again after setting up a fresh one.
In some cases firmware files won't be available any more ...

**Comment by Jo-Be-Co** [comment]
By the way @phdelodder.

Just read the OTAU part in the readme: [link](https://github.com/deconz-community/deconz-docker#notes-on-otau-over-the-air-updates)

The mentioned folder differs from the one stated in the readme from [deconz-ota-plugin](https://github.com/dresden-elektronik/deconz-ota-plugin). Which one is correct?

**Comment by Jo-Be-Co** [comment]
I see. I think I took the path from the script as the one that is used by the plugin itself. Anyway if you do have access to the folder from the host (a maybe also via a network share ...) - is there still the need to run a scheduled job from inside the container?

**Comment by SkipperDo** [comment]
I just want an automatic check & download if new firmware available every x days... my first idea was a crontab in the Container.. But if any other / better ideas to realize....

**Comment by senilio** [comment]
I agree that running a cron job on the docker host is the way to do this... just save the files where deCONZ expects to find them.  If you still want to have a go at getting this script running inside the container, you can always submit a PR and we'll be happy to review.
