### ISSUE TITLE
restarting loop

### ISSUE THREAD

**Issue by flobbr** [deconz-community/deconz-docker#97]
Hi, i have a issues since today after the container ran perfect for a few month:
die container starts and directly restarts.
The log shows the following:

> [deconzcommunity/deconz] Starting deCONZ...
> [deconzcommunity/deconz] Current deCONZ version: 2.13.04
> [deconzcommunity/deconz] Web UI port: 8888
> [deconzcommunity/deconz] Websockets port: 443
> [deconzcommunity/deconz] Modifying user and group ID
> [deconzcommunity/deconz] Checking device group ID
> [deconzcommunity/deconz] VNC port: 5901
> Use of uninitialized value in pattern match (m//) at /usr/bin/tigervncserver line 490.
> tigervncserver: Can't parse pid file '/home/deconz/.vnc/9780ba8a4d7f:1.pid'!
> Use of uninitialized value in pattern match (m//) at /usr/bin/tigervncserver line 490.
> tigervncserver: Can't parse pid file '/home/deconz/.vnc/9780ba8a4d7f:1.pid'!
> A VNC/X11 server is already running as :1 on machine 9780ba8a4d7f
> 
> Warning: 9780ba8a4d7f:1 is taken because of /tmp/.X1-lock
> Remove this file if there is no X server 9780ba8a4d7f:1
> WebSocket server settings:
>   - Listen on :6080
>   - Flash security policy server
>   - Web server. Web root: /usr/share/novnc
>   - SSL/TLS support
>   - Backgrounding (daemon)
> [deconzcommunity/deconz] NOVNC port: 6080
> qt.qpa.screen: QXcbConnection: Could not connect to display :1
> Could not connect to any X display.

I started it with the following command:
`sudo docker run -d     --name=deconz     --restart=always     -p 8888:8888     -p 443:443     -p 6080:6080     -p 5901:5901     -v /etc/localtime:/etc/localtime:ro     -v /opt/deconz:/opt/deCONZ     -e DECONZ_WEB_PORT=8888     -e DECONZ_VNC_MODE=1     -e DECONZ_VNC_PASSWORD=**********     -e DECONZ_VNC_PORT=5901     --device=/dev/ttyACM0     deconzcommunity/deconz:stable`

Anybody knows how i can fix this?

**Comment by NicciNO** [comment]
No clue, but turn off VNC mode and it should start. I got the same issue on my Synology.

**Comment by phdelodder** [comment]
perhapse try to remove the vnc in /opt/deCONZ folder

**Comment by senilio** [comment]
This issue is clearly due to tigervncserver not being able to access its files. Doing what's suggested above should solve the issue.
