### ISSUE TITLE
New Version: Assertion `deviceUniqueId.size() == 23' failed.`

### ISSUE THREAD

**Issue by asktimfisher** [deconz-community/deconz-docker#98]
Just updated to the latest version and now nothing loads. Logs show:

deCONZ: ../../../../deconz/src/plugins/de_web/database.cpp:6625: std::vector<DB_ResourceItem> DB_LoadSubDeviceItemsOfDevice(QLatin1String): Assertion `deviceUniqueId.size() == 23' failed.

Thoughts?

**Comment by asktimfisher** [comment]
Not sure what caused this, but I tried spinning up a new container with the previous version (and then the last stable one) and I got the same results. To correct this, I created a brand new (from scratch) container with the last stable release (just to be safe) and restored a recent backup. All good. So who knows!

**Comment by senilio** [comment]
Are you running deCONZ on Synology?

I assume these are the steps to fix:

1. Stop container
2. Delete container - docker rm container_id
3. Start a new container
